[{"owner":{"profile_image":"https://i.stack.imgur.com/vNRRo.jpg?s=256&g=1","account_id":3514618,"user_type":"registered","user_id":2938364,"link":"https://stackoverflow.com/users/2938364/markus-weninger","reputation":12090,"display_name":"Markus Weninger","accept_rate":88},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/72598626/official-recommendation-coding-style-guide-on-using-multiple-throws-tags-for","last_activity_date":1655113252,"creation_date":1655102168,"answer_count":2,"title":"Official recommendation / coding style guide on using multiple @throws tags for the same exception in JavaDoc","body":"<p>I just recently found out that <a href=\"https://stackoverflow.com/questions/9229991/can-i-use-multiple-throws-tags-for-the-same-exception-in-javadoc\">one can use multiple <code>@throws</code> tags for the same exception in Javadoc</a>.</p>\n<p>One of my students used it to document one of his methods in <a href=\"https://en.wikipedia.org/wiki/Connect_Four\" rel=\"noreferrer\">Connect Four</a>:</p>\n<pre><code>/*\n * ...\n * @throws IllegalArgumentException if the number of rows or columns is invalid \n * @throws IllegalArgumentException if one of the players has {@link Stone#None} as stone\n * @throws IllegalStateException if both players use the same stone color\n */\npublic void doSomething(...) { ... }\n</code></pre>\n<p>Now my (and his) question: Is there an official style guide or a general recommendation on whether to use a single <code>@throws</code> tag or &quot;is it fine&quot; to use multiple ones per exception type?</p>\n","question_id":72598626,"tags":["java","exception","javadoc","code-documentation","throws"],"score":7,"accepted_answer_id":72600530,"is_answered":true,"view_count":267},{"owner":{"profile_image":"https://www.gravatar.com/avatar/4d14bb9e5c27d2d26f8f6f011cc4571a?s=256&d=identicon&r=PG","account_id":1442354,"user_type":"registered","user_id":1362082,"link":"https://stackoverflow.com/users/1362082/franz","reputation":1913,"display_name":"Franz","accept_rate":53},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/72595022/throw-own-defined-exception-in-visitor-pattern-java","last_activity_date":1655063114,"creation_date":1655060037,"answer_count":1,"title":"throw own defined exception in visitor pattern java","body":"<p>We  have to  write an app using the visitor design pattern  like ( <a href=\"https://www.baeldung.com/java-visitor-pattern\" rel=\"nofollow noreferrer\">https://www.baeldung.com/java-visitor-pattern</a> ) , one example  element looks like, implementing interface Stmt :</p>\n<pre><code>public class Call implements Stmt {\n    int hash_id;\n    private String id;\n    public Call(String id )   { this.id = id;}\n\n\n    public void accept(Visitor v) {\n        System.out.println(&quot;call.accept&quot;);\n        v.visit( this);\n    }\n\n    public String getId () {  return id;}\n    ....}\n</code></pre>\n<p>The vistor Interface  looks like this  code below , I may not change the  interface  code.</p>\n<pre><code>public interface Visitor {\n    ... \n    ...\n\n    void visit(Subroutine subroutine);\n\n    void visit(Call call);\n}\n</code></pre>\n<p>Inside the  Implementation  of an  Visitor (AbstractVisitor class) I have to throw a &quot;UndefinedSubroutineException if the id (type string)  of a call class is not yet  existing  in the hashtable SubBefehle.\nThe existing  code with try catch statemenets never send as an exception  to my testcase ....</p>\n<pre><code>public abstract class AbstractVisitor implements Visitor {\n.....\n private Hashtable&lt;String, Integer&gt; SubBefehle = new Hashtable&lt; String, Integer&gt;();\n\n@Override\npublic void visit(Call call)  {\n    ///  implementation work :\n\n       try {\n\n           IsFunctionNameExisting(call.getId());\n       }\n       catch (UndefinedSubroutineException e){\n          // throw new UndefinedSubroutineException(&quot;&quot;);\n       }\n}\n\npublic void IsFunctionNameExisting(String fctname) throws UndefinedSubroutineException {\n    boolean IsFound = false;\n\n    if (SubBefehle.containsKey(fctname)) {\n        System.out.println(&quot;Abstract visitor :  function name found -&gt; PASS  &quot;);\n        IsFound = true;\n    }\n    else {\n        System.out.println(&quot;Abstract visitor : function name not yet found -&gt; EXCEPTION &quot;);\n         throw new UndefinedSubroutineException(&quot; function name not found in function name list !&quot;);\n    }\n</code></pre>\n<p>if the call IsFunctionNameExisting(call.getId()) is false if the name is not found inside the hash table. My optional solution is also not working .</p>\n<pre><code>///  optional solution \n@Override\npublic void visit(Call call) throws UndefinedSubroutineException  {\n    ///  implementation work :\n           IsFunctionNameExisting(call.getId());\n       }\n</code></pre>\n<p>the corresponding testcase looks like this :</p>\n<pre><code>@Test \npublic void testUndefinedSubroutine() {\n    try {\n        PROG_TEST.accept(testVisitor);\n        fail(&quot;Exception expected&quot;);\n    } catch (UndefinedSubroutineException e) {\n       ........\n    }\n}\n</code></pre>\n<p>package turtle.logo;</p>\n<p>the defintion  of UndefinedSubroutineException goes like  this :</p>\n<pre><code>public class UndefinedSubroutineException  extends Throwable {\n\n    public  UndefinedSubroutineException (String message) {\n\n        super(message);\n    }\n}\n</code></pre>\n<p>PS:  I can't  change the test cases and the interface  definition  &amp;<br />\nI hope someone can help us with this problem.</p>\n","question_id":72595022,"tags":["java","exception","visitor-pattern"],"score":0,"is_answered":true,"view_count":92,"last_edit_date":1655063114},{"owner":{"profile_image":"https://www.gravatar.com/avatar/7c7ce5a047c15f100e5f8e224078d19a?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":16720659,"user_type":"registered","user_id":12085680,"link":"https://stackoverflow.com/users/12085680/bugsoverflow","reputation":408,"display_name":"BugsOverflow"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/72582682/restcontrolleradvice-stops-working-properly-when-using-responsestatus-too","last_activity_date":1654950608,"creation_date":1654934788,"answer_count":1,"title":"@RestControllerAdvice Stops Working Properly when using @ResponseStatus too","body":"<p>I am using RestControllerAdvice to return custom responses dependending on the type of exception that happened (they are all runtime exceptions), this was the first time that I used it today and it was a very weird experience because at testing with postman and local it worked perfectly, but when we deployed to Quality it just did not work, everytime when there was an exception, the frontend did not even get any response, but in postman it kept working when making the exact request, so after like 5 hours of trying different things I tried removing the @ResponseStatus annotation and then it started responding properly to the frontend when exceptions happened, maybe I missed something about this annotation, here is the code of my RestControllerAdvice that does not work properly (when call from frontend):</p>\n<pre><code>@RestControllerAdvice\npublic class SftpExceptionHandler {\n\n    @ExceptionHandler(FileTypeNotFoundException.class)\n    @ResponseStatus(HttpStatus.NOT_FOUND)\n    public GeneralResponse handlerRequestException(FileTypeNotFoundException ex) {\n        return new GeneralResponse(HttpStatus.NOT_FOUND, ex.getMessage());\n    }\n\n    @ExceptionHandler(IncorrectConsecutiveException.class)\n    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)\n    public GeneralResponse handlerRequestException(IncorrectConsecutiveException ex) {\n        return new GeneralResponse(HttpStatus.INTERNAL_SERVER_ERROR, ex.getMessage());\n    }\n\n    @ExceptionHandler(InvalidBinaryFileException.class)\n    @ResponseStatus(HttpStatus.BAD_REQUEST)\n    public GeneralResponse handlerRequestException(InvalidBinaryFileException ex) {\n        return new GeneralResponse(HttpStatus.BAD_REQUEST, ex.getMessage());\n    }\n\n}\n</code></pre>\n<p>Any idea why ResponseStatus annotation makes it fail? If I remove it then the frontend starts being able to read the response properly like the postman</p>\n<p>Example of one of my custom exceptions:</p>\n<pre><code>public class InvalidBinaryFileException extends RuntimeException {\n\n    private static final long serialVersionUID = 1L;\n\n    public InvalidBinaryFileException(String message) {\n        super(message);\n    }\n}\n</code></pre>\n","question_id":72582682,"tags":["java","spring-boot","rest","exception"],"score":0,"accepted_answer_id":72584310,"is_answered":true,"view_count":436},{"owner":{"profile_image":"https://www.gravatar.com/avatar/a771ce5c75531b9171379df1e7429c87?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":17400576,"user_type":"registered","user_id":12609542,"link":"https://stackoverflow.com/users/12609542/david-blbulyan","reputation":35,"display_name":"David Blbulyan"},"closed_date":1654875510,"link":"https://stackoverflow.com/questions/72576694/how-can-i-force-to-work-option-binarry-class-files-in-idea-gui-designer-settin","last_activity_date":1654875371,"creation_date":1654874920,"answer_count":0,"title":"How can I force to work option &quot;binarry class files&quot; in IDEA GUI Designer settings?","body":"<p>I have a problem with running my GUI application, when I run my jar file. I get exception:</p>\n<pre><code>Exception in thread &quot;main&quot; java.awt.IllegalComponentStateException: contentPane cannot be set to null.\n    at java.desktop/javax.swing.JRootPane.setContentPane(JRootPane.java:594)\n    at java.desktop/javax.swing.JDialog.setContentPane(JDialog.java:1036)\n    at ui.ConnectToServerDialog.&lt;init&gt;(ConnectToServerDialog.java:22)\n    at common.Client.main(Client.java:14)\n</code></pre>\n<p>This is the rather common mistake. I read solutions, but everyone writes: &quot;choice java source code option&quot;, but it's uncomfortable for me, it fouls my code.\nI talk about this settings page in IDEA:\n<a href=\"https://i.stack.imgur.com/s6ERP.png\" rel=\"nofollow noreferrer\">gui designer settings screenshoot</a></p>\n<p>So, how can I fix the &quot;binary class files option&quot;?\nI create the dialog using Swing UI Designer in IDEA</p>\n","question_id":72576694,"tags":["java","user-interface","exception","intellij-idea"],"score":0,"closed_reason":"Duplicate","is_answered":false,"view_count":16,"last_edit_date":1654875371},{"owner":{"profile_image":"https://lh3.googleusercontent.com/a/AATXAJwVmYWkqfnXF0sDDhbWRtfXo8P2Eb5K_HIOPC-M=k-s256","account_id":25436265,"user_type":"registered","user_id":19239939,"link":"https://stackoverflow.com/users/19239939/batter","reputation":21,"display_name":"Batter"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/72559219/com-sun-tools-attach-agentloadexception-102-when-attaching","last_activity_date":1654773482,"creation_date":1654772787,"answer_count":0,"title":"com.sun.tools.attach.AgentLoadException: 102 when attaching","body":"<p>Stack Trace:</p>\n<pre><code>com.sun.tools.attach.AgentLoadException: 102\n    at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:109)\n    at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:120)\n    at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:148)\n    at Main.main(Main.java:31)\n</code></pre>\n<p>Code:</p>\n<pre><code>try {\n            attach.loadAgent(agent.getAbsolutePath() , &quot;1&quot;);\n            System.out.println(&quot;Agent was loaded.&quot;);\n        } catch (AgentLoadException e) {\n            System.err.println(&quot;Agent failed to load: &quot;);\n            e.printStackTrace();\n        } catch (AgentInitializationException e) {\n            System.err.println(&quot;Agent loaded, but failed to initialize: &quot;);\n            e.printStackTrace();\n        } catch (IOException e) {\n            e.printStackTrace();\n        }\n</code></pre>\n<p>Trying to attach an agent to a VM\nI get AgentLoadException:102\n102 upon looking up is ATTACH_ERROR_STARTFAIL\nAny ideas on how can I solve it?\nthanks.</p>\n","question_id":72559219,"tags":["java","exception","virtual-machine"],"score":2,"is_answered":false,"view_count":147,"last_edit_date":1654773482},{"owner":{"profile_image":"https://www.gravatar.com/avatar/02246f35e9f5c91a9d99a08b378e686c?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":3931956,"user_type":"registered","user_id":3250086,"link":"https://stackoverflow.com/users/3250086/garyf","reputation":521,"display_name":"garyF"},"content_license":"CC BY-SA 3.0","link":"https://stackoverflow.com/questions/46091211/is-it-possible-to-resume-java-execution-after-exception","last_activity_date":1654755149,"creation_date":1504771805,"answer_count":3,"title":"Is it possible to resume Java execution after exception?","body":"<p>I have a ParentClass in a JAR, but not source code. I am implementing a SubClass, but i need to handle some corner cases.</p>\n\n<pre><code>class ParentClass {\n    void foo() {\n       … // lots of code 1\n       ; // can possibly throw NullPointerException \n       … // lots of code 2\n    }\n}\nclass SubClass extends ParentClass {\n    @Override\n    void foo() {\n       try {super.foo();}\n       catch(NullPointerException npe) {… /*handle exception*/}\n       finally {… /* resume lots of code 2 ? */}\n    }\n}\n</code></pre>\n\n<p>Is there a way to run the <code>//lots of code 2</code> part after handling the exception in the overriding method? I don't want to duplicate code, and cannot modify the ParentClass.</p>\n\n<p>P.S: The NullPointerException problem wasn't there in the ParentClass. But due to a different instantiation in SubClass, this problem may arise.</p>\n","question_id":46091211,"tags":["java","exception"],"score":5,"accepted_answer_id":46091271,"is_answered":true,"view_count":1159,"last_edit_date":1504772008},{"owner":{"profile_image":"https://lh3.googleusercontent.com/a/AATXAJzvamS-Qd3JPEKG7qqnzv1bmepOP3e5z8SZ-JSxAA=k-s256","account_id":25510797,"user_type":"registered","user_id":19302492,"link":"https://stackoverflow.com/users/19302492/santurron","reputation":1,"display_name":"santurron"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/72552971/what-is-the-best-way-to-prevent-the-program-from-breaking-when-receiving-a-user","last_activity_date":1654729229,"creation_date":1654728282,"answer_count":1,"title":"what is the best way to prevent the program from breaking when receiving a user input in java?","body":"<p>I learned exceptions with try catch, but i dont know if this is the propper way to secure the program. For example, when i use a scan.nextint, and the user enters a string, what is the best way to prevent that? Try catch, or something else?</p>\n","question_id":72552971,"tags":["java","validation","exception","input","java.util.scanner"],"score":-1,"is_answered":false,"view_count":32},{"owner":{"profile_image":"https://www.gravatar.com/avatar/28d7fc76db803c6757e7cfd2cde20354?s=256&d=identicon&r=PG","account_id":31293,"user_type":"registered","user_id":85821,"link":"https://stackoverflow.com/users/85821/bart-van-heukelom","reputation":43494,"display_name":"Bart van Heukelom","accept_rate":73},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/72546743/outofmemoryerror-is-dangerous-but-why-more-dangerous-than-other-exceptions","last_activity_date":1654696757,"creation_date":1654695667,"answer_count":3,"title":"OutOfMemoryError is dangerous, but why more dangerous than other exceptions?","body":"<p>Conventional wisdom, on this site and elsewhere, is to not catch <code>java.lang.OutOfMemoryError</code>, except maybe for cleaning up, and just let the JVM crash and be restarted. The reason given for this is that it may have left the process in an invalid state. Okay, that seems like a good reason.</p>\n<p>But... that's not exclusive to <code>OutOfMemoryError</code>. Any exception may have left invalid state if it's not properly handled. Why is this considered okay:</p>\n<pre><code>String handleRequest(String name) {\n    try {\n        if (name.equals(&quot;buggy&quot;)) return buggy();\n        else if (name.equals(&quot;hungry&quot;)) return hungry();\n        else throw new IllegalArgumentException();\n    } catch (Exception e) { // &lt;-- not catching OutOfMemoryError\n        return &quot;Error: &quot; + e;\n    }\n}\n\nString buggy() {\n     bunnyLock.lock();\n     // oops! can throw ArrayIndexOutOfBoundsException due to using round instead of floor\n     var res = bunnies[(int) Math.round(Math.random() * bunnies.length)];\n     bunnyLock.unlock();\n    return res;\n}\n\nString hungry() {\n     var b = new byte[2_000_000_000]; // 2 GB because why not\n     ...\n}\n</code></pre>\n<p>But changing the catch to <code>Throwable</code> isn't? The <code>ArrayIndexOutOfBoundsException</code> is somehow considered more safe to catch, yet <code>buggy</code> is the method that leaves the state invalid, while a failed allocation in <code>hungry</code> is no problem.</p>\n<p>You might say, well, you should fix <code>buggy</code> to never leave state invalid:</p>\n<pre><code>String buggy() {\n     bunnyLock.lock();\n     try {\n         // oops! can throw ArrayIndexOutOfBoundsException due to using round instead of floor\n         return bunnies[(int) Math.round(Math.random() * bunnies.length)];\n     } finally {\n         bunnyLock.unlock();\n     }\n}\n</code></pre>\n<p>And I'd agree. In fact, I agree so much that I think every piece of code everywhere should be exception-safe like that. Then you may safely assume that even an <code>OutOfMemoryError</code> has not left any state invalid.</p>\n<p>So, am I missing something and is <code>OutOfMemoryError</code> really more dangerous?</p>\n","question_id":72546743,"tags":["java","exception","out-of-memory","indexoutofboundsexception"],"score":0,"accepted_answer_id":72547035,"is_answered":true,"view_count":157},{"owner":{"user_type":"does_not_exist","display_name":"user843337"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/8895091/how-can-i-set-the-message-on-an-exception-in-java","last_activity_date":1654621751,"creation_date":1326805549,"answer_count":8,"title":"How can I set the message on an exception in Java?","body":"<p>I want to set a custom exception message. However, I'm unsure of how to do this. Will I need to create a custom exception class or is there an easier way of doing this?</p>\n","question_id":8895091,"tags":["java","exception"],"score":26,"accepted_answer_id":8895131,"is_answered":true,"view_count":101042,"last_edit_date":1598921291},{"owner":{"profile_image":"https://www.gravatar.com/avatar/f7cf53bd8e67338b36d086f48477edfa?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":22531657,"user_type":"registered","user_id":16723586,"link":"https://stackoverflow.com/users/16723586/kiznet007","reputation":15,"display_name":"Kiznet007"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/70008079/catching-exceptions-on-multiple-inputs-from-user-but-not-go-back-to-first-input","last_activity_date":1654610205,"creation_date":1637166287,"answer_count":4,"title":"Catching exceptions on multiple inputs from user but not go back to first input","body":"<p>Here is a small program that has multiple inputs from the user to get the smallest number entered. I'm trying to catch the InputMismatchException all in the same try/catch block but if the user inputs anything but an int on say the second or third int to be entered then it jumps back to the first input which the user already entered correctly. Is there a simpler way to fix this or do I need to create separate try/catch blocks for each input?</p>\n<pre><code>    public class GrabbingSmallestValueEntered {\n        \n        public static void main(String[] args) {\n            \n            //Scanner input = new Scanner(System.in);\n            boolean correctInput = true;\n            double a = 0;\n            double b = 0;\n            double c = 0;\n        \n            Scanner input = new Scanner(System.in);\n    \n                do {\n                    \n                    try {\n                    \n                    System.out.println(&quot;Input the first number: &quot;);\n                        a = input.nextDouble();\n                        \n                    System.out.println(&quot;Input the second number: &quot;);\n                        b = input.nextDouble();\n                        \n                    System.out.println(&quot;Input the third number: &quot;);\n                        c = input.nextDouble();\n                        correctInput = false;\n                    \n                }catch (InputMismatchException ie) {\n                    System.out.println(&quot;Only numbers allowed to be entered. No letters or words!&quot;);\n                    input.nextLine();\n                }\n    \n                \n            } while (correctInput);\n            \n                System.out.println(&quot;The smallest value is &quot; + smallest(a, b, c) + &quot;\\n&quot;);\n                \n}\n\npublic static double smallest(double a, double b, double c)\n{ \n\n  return Math.min(Math.min(a, b), c);\n}\n    \n    \n</code></pre>\n","question_id":70008079,"tags":["java","exception","input","try-catch"],"score":0,"is_answered":true,"view_count":904,"last_edit_date":1637198948},{"owner":{"profile_image":"https://lh3.googleusercontent.com/a/AATXAJwC88Hs0im1KqVpg1tDjWY0uWcimaxqZmOQbO-Y=k-s256","account_id":22839847,"user_type":"registered","user_id":16987056,"link":"https://stackoverflow.com/users/16987056/xx-x","reputation":1,"display_name":"xx x"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/69923637/indexoutofboundsexception-when-writing-a-list-of-players-to-a-file","last_activity_date":1636844095,"creation_date":1636608997,"answer_count":1,"title":"IndexOutOfBoundsException when writing a list of players to a file","body":"<p>I'm working on assignment for OOP and am stuck on the last step which is, &quot;Write all players to an output file that has a similar format of the input file.&quot;</p>\n<p>I need to know how to print all the info in the main to an output file with the same format as the input file and I use here ArrayList. it's working fine when I print the name and the height but when I want to print season or score, an exception appears.</p>\n<pre><code>pw.write(t1.getName() + &quot;; &quot; + t1.getCity() + &quot;\\n&quot;);\nfor (int m = 0; m &lt; p2.size(); m++) {\n    pw.print(t1.getPlayerList().get(m).getName() + &quot;; &quot; + t1.getPlayerList().get(m).getHeight() + &quot;; &quot;);\n    pw.println(t1.getPlayerList().get(m).getSeasonalRecords().get(m).getScores());\n} \n</code></pre>\n<p>it works well, but when I write</p>\n<pre><code>pw.println(t1.getPlayerList().get(m).getSeasonalRecords().get(m).getScores());\n</code></pre>\n<p>appear something is wrong\nthat the exceptions that I got</p>\n<blockquote>\n<p>Exception in thread &quot;main&quot; java.lang.IndexOutOfBoundsException: Index: 2, Size: 2\nat java.util.ArrayList.rangeCheck(ArrayList.java:657)\nat java.util.ArrayList.get(ArrayList.java:433)</p>\n</blockquote>\n","question_id":69923637,"tags":["java","exception","arraylist"],"score":-1,"is_answered":false,"view_count":92,"last_edit_date":1636609701},{"owner":{"profile_image":"https://lh4.googleusercontent.com/-XO5pmVBQa3Y/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucnEnwT2r9D_vvE0tEkG_cwkXTZaXg/photo.jpg?sz=256","account_id":18554741,"user_type":"registered","user_id":13520144,"link":"https://stackoverflow.com/users/13520144/brunner-arthur","reputation":1,"display_name":"Brunner Arthur"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/69935845/java-lang-classnotfoundexception-net-sf-jasperreports-engine-jrexception","last_activity_date":1636741913,"creation_date":1636670564,"answer_count":1,"title":"java.lang.ClassNotFoundException: net.sf.jasperreports.engine.JRException","body":"<p>I am building a school management which needs to include terminal reports. I am using jasperreports but when I  run the codes in intellij, the reports are shown. But when I create the jar file and run the it, this is the error i encounter from the console .</p>\n<p>java.lang.ClassNotFoundException: net.sf.jasperreports.engine.JRException</p>\n","question_id":69935845,"tags":["java","exception","intellij-idea","compilation","report"],"score":0,"is_answered":false,"view_count":2762},{"owner":{"profile_image":"https://www.gravatar.com/avatar/446285f789b43eb050f92f100a7e7153?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":11389024,"user_type":"registered","user_id":8349761,"link":"https://stackoverflow.com/users/8349761/thu-vix","reputation":43,"display_name":"thu.vix"},"closed_date":1661652725,"link":"https://stackoverflow.com/questions/69945215/unreported-exception-despite-of-try-catch-block","last_activity_date":1636730939,"creation_date":1636730598,"answer_count":1,"title":"unreported exception despite of try-catch block","body":"<p>I'm writing a program to practice throwing exceptions, and get compile error in one of the test:</p>\n<p>MyTest.java:29: error: unreported exception FileNotFoundException; must be caught or declared to be thrown:</p>\n<p>Assert.assertEquals(&quot;File Not Found&quot;, task2.fileNotFoundExTest());</p>\n<p>^</p>\n<pre><code>public void fileNotFoundEx() throws FileNotFoundException {\n        File fileName = new File(&quot;foo.txt&quot;);\n        BufferedReader rd = new BufferedReader(new FileReader(fileName));\n    }\n\npublic String fileNotFoundExTest() throws FileNotFoundException {\n        try {\n            fileNotFoundEx();\n        } catch (FileNotFoundException e) {\n            return &quot;File Not Found&quot;;\n        }\n        return &quot;No Error&quot;;\n    }\n</code></pre>\n<p>I don't know why this error occurs because I already put the method that causes exception in a try-catch block and add signature &quot;throws FileNotFoundException&quot; to both methods. Can anyone explain this?</p>\n","question_id":69945215,"tags":["java","exception"],"score":0,"accepted_answer_id":69945286,"closed_reason":"Duplicate","is_answered":true,"view_count":160},{"owner":{"profile_image":"https://i.stack.imgur.com/ojvZh.jpg?s=256&g=1","account_id":1316033,"user_type":"registered","user_id":1262865,"link":"https://stackoverflow.com/users/1262865/john16384","reputation":7855,"display_name":"john16384","accept_rate":50},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/69944374/any-downsides-to-rethrowing-the-cause-of-a-checked-exception-as-an-unchecked-e","last_activity_date":1636727285,"creation_date":1636726825,"answer_count":0,"title":"Any downsides to rethrowing the *cause* of a checked exception as an unchecked exception?","body":"<p>I am writing a library in which I use checked exceptions internally as it helps to make sure that all paths handle certain exceptional cases. However, I don't want to burden the users of my library with these checked exceptions because of this rule I use:</p>\n<blockquote>\n<p>Exceptions should only be checked when they're out of control of both the caller and receiver.</p>\n</blockquote>\n<p>As most of the internal checked exceptions point to configuration problems or other issues that would never occur in a correct setup (and thus can be solved by the user), I wish to expose these as unchecked exceptions at my API boundaries.</p>\n<p>Normally, I would wrap these checked exceptions in an unchecked variant and be done with it. However, in this library, I sometimes have 3 levels of exception nesting already, for example:</p>\n<pre><code>hs.ddif.core.inject.instantiator.CheckedInstantiationException: Exception while constructing instance via Producer: hs.ddif.core.inject.instantiator.InstantiatorTest$H hs.ddif.core.inject.instantiator.InstantiatorTest$B.createH()\n(...)\nCaused by: java.lang.reflect.InvocationTargetException\n(...)\nCaused by: java.lang.RuntimeException: can't create H\n</code></pre>\n<p>Adding another level on top (which will not really add any relevant information) makes it harder to see the underlying cause and would require <code>instanceof</code> checks on <code>getCause</code> if user code does want to do specific handling. I currently do this:</p>\n<pre><code>catch(CheckedInstantiationException e) {\n    throw new InstantiationException(e);  // convert to runtime at API boundary\n}  \n</code></pre>\n<p>But what if I did this instead:</p>\n<pre><code>catch(CheckedInstantiationException e) {\n    throw new InstantiationException(e.getMessage(), e.getCause());  // convert to runtime at API boundary\n}  \n</code></pre>\n<p>This strips one nesting level but keeps the trace intact.  The trace looks slightly different, but still includes all lines involved.</p>\n<p>My question is, does this approach have any down sides that I'm missing?</p>\n","question_id":69944374,"tags":["java","exception","checked-exceptions","rethrow"],"score":2,"is_answered":false,"view_count":79,"last_edit_date":1636727285},{"owner":{"profile_image":"https://i.stack.imgur.com/shfxy.jpg?s=256&g=1","account_id":8604130,"user_type":"registered","user_id":6444776,"link":"https://stackoverflow.com/users/6444776/ommadawn","reputation":2552,"display_name":"Ommadawn","accept_rate":84},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/69940918/hibernate-java-lang-illegalstateexception-transaction-already-active","last_activity_date":1636711601,"creation_date":1636710594,"answer_count":1,"title":"Hibernate java.lang.IllegalStateException: Transaction already active","body":"<p>I'm using Java EE + Hibernate 5 and recently I can see I've got some error messages in my Tomcat 9 logs saying:</p>\n<p><code>java.lang.IllegalStateException: Transaction already active</code></p>\n<p>The methods involved in the issue are:</p>\n<pre><code>// The caller method\nPic p = picDAO.getById(1000);\n\n\n// The Hibernate method\n@Override\npublic Pic getById(Integer id) throws BDException {\n    Session session = sessionFactory.getCurrentSession();\n    Transaction tx = session.getTransaction();\n    try {\n        tx.begin();\n        Pic p = (Pic) session.get(myClass, id);\n        tx.commit();\n        return p;\n    }\n    catch(........) {\n        // Exceptions here\n    }\n}\n</code></pre>\n<p>Edit. Here is the full stack trace (some messages are in spanish):</p>\n<pre><code>12-Nov-2021 09:30:43.875 GRAVE [http-nio-8080-exec-10] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() para servlet [ViewPic] lanzó excepción\n        java.lang.IllegalStateException: Transaction already active\n                at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:74)\n                at project.dao.DAOGeneric.getById(DAOGeneric.java:268)\n                at project.controller.forwards.ViewPic.processRequest(ViewPic.java:86)\n                at project.controller.MainServlet.doGet(MainServlet.java:38)\n                at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)\n                at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)\n                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)\n                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)\n                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n                at project.controller.filters.TileConfigFilter.doFilter(TileConfigFilter.java:58)\n                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)\n                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)\n                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)\n                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)\n                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)\n                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)\n                at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)\n                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)\n                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)\n                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)\n                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)\n                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)\n                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n                at java.base/java.lang.Thread.run(Thread.java:829)\n</code></pre>\n","question_id":69940918,"tags":["java","hibernate","session","tomcat","exception"],"score":0,"accepted_answer_id":69941125,"is_answered":true,"view_count":743,"last_edit_date":1636711193},{"owner":{"profile_image":"https://i.stack.imgur.com/TaCMM.jpg?s=256&g=1","account_id":1242916,"user_type":"registered","user_id":1205066,"link":"https://stackoverflow.com/users/1205066/sergey","reputation":437,"display_name":"Sergey","accept_rate":100},"content_license":"CC BY-SA 3.0","link":"https://stackoverflow.com/questions/23625440/design-pattern-for-cumulative-validation-violations","last_activity_date":1636636754,"creation_date":1399966950,"answer_count":5,"title":"Design pattern for cumulative validation violations","body":"<p>Let's imagine, that we have a process, which accepts data of the following type:</p>\n\n<pre><code>{\"date\":\"2014-05-05\", \"url\":\"http://some.website.com\",\"counter\":3}\n</code></pre>\n\n<ul>\n<li>This data should be validated <strong>formally</strong>: value of <code>date</code> should be a\nparseable date, <code>url</code> should also conform the normal url syntax.</li>\n<li>Also, this data should be validated <strong>logically</strong>: <code>date</code> should be in the future, <code>url</code> should be an accessible\naddress, returning <code>200 OK</code>.</li>\n</ul>\n\n<p>To make it clean, one must separate those two validation routines into different units (classes, utils, whatever). The desired final behaviour, however, must give user clear understanding of ALL violations, that are present in data. Something like: </p>\n\n<p><code>{\"Errors\":[\n     \"Specified date is not in the future\",//Formal validation failed\n     \"Specified URL has invalid syntax\"//Logical validation failed\n ]}</code></p>\n\n<ul>\n<li>I have seen some implementations of the required behaviour, but they\nuse those make use of <code>Error</code> objects and are full of checks like\n<code>Error.hasErrors()</code> or <code>error==null</code>, which does not look elegant.</li>\n<li>I have also seen the implementation of <code>javax.validation</code>, which gives you all violations  on all field at once. Same approach could be implemented for content validation, but I am not sure, that this is the best way to do this. </li>\n</ul>\n\n<p><strong>Question</strong>: what is the best practice for handling multiple exceptions/violations of various nature?</p>\n\n<p><strong>UPD:</strong> short digest of answers: collect <code>Violations</code>, build an <code>Exception</code>, containing their context, cause and description, use an interceptor to render. See reference links from answers:</p>\n\n<p><a href=\"http://beanvalidation.org/1.0/spec/\" rel=\"nofollow noreferrer\">http://beanvalidation.org/1.0/spec/</a> JSR 303 specification</p>\n\n<p><a href=\"http://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/validation.html\" rel=\"nofollow noreferrer\">http://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/validation.html</a> Spring Bean Validation</p>\n\n<p><a href=\"http://docs.oracle.com/javaee/6/tutorial/doc/gircz.html\" rel=\"nofollow noreferrer\">http://docs.oracle.com/javaee/6/tutorial/doc/gircz.html</a> Java EE validation</p>\n\n<p><a href=\"https://stackoverflow.com/questions/18314609/which-design-pattern-to-use-for-validation\">Which Design Pattern To Use For Validation</a></p>\n\n<p><a href=\"https://stackoverflow.com/questions/729379/why-not-use-exceptions-as-regular-flow-of-control\">Why not use exceptions as regular flow of control?</a></p>\n","question_id":23625440,"tags":["java","validation","design-patterns","exception"],"score":6,"accepted_answer_id":23625868,"is_answered":true,"view_count":4374,"last_edit_date":1495542721},{"owner":{"profile_image":"https://www.gravatar.com/avatar/e6d1d662f2b3873887e61dafbed6d2c1?s=256&d=identicon&r=PG","account_id":42657,"user_type":"registered","user_id":124339,"link":"https://stackoverflow.com/users/124339/johanna","reputation":27146,"display_name":"Johanna","accept_rate":46},"content_license":"CC BY-SA 3.0","link":"https://stackoverflow.com/questions/1070590/how-can-i-write-custom-exceptions","last_activity_date":1636527910,"creation_date":1246472266,"answer_count":5,"title":"How can I write custom Exceptions?","body":"<p>How can I create a new <code>Exception</code> different from the pre-made types?</p>\n\n<pre><code>public class InvalidBankFeeAmountException extends Exception{\n    public InvalidBankFeeAmountException(String message){\n        super(message);\n    }\n }\n</code></pre>\n\n<p>It will show the warning for the <strong>InvalidBankFeeAmountException</strong> which is written in the first line.</p>\n","question_id":1070590,"tags":["java","exception"],"score":54,"accepted_answer_id":1070593,"is_answered":true,"view_count":57110,"last_edit_date":1438251126},{"owner":{"profile_image":"https://www.gravatar.com/avatar/d172333ccceefbcc91c2f38bbd30b332?s=256&d=identicon&r=PG","account_id":2489985,"user_type":"registered","user_id":2167671,"link":"https://stackoverflow.com/users/2167671/isaac-smith","reputation":173,"display_name":"Isaac Smith"},"content_license":"CC BY-SA 3.0","link":"https://stackoverflow.com/questions/15398703/exception-in-thread-main-java-util-nosuchelementexception","last_activity_date":1636471521,"creation_date":1363218627,"answer_count":6,"title":"Exception in thread &quot;main&quot; java.util.NoSuchElementException","body":"<p>Whenever I run this, the <code>chooseCave()</code> function works fine with the <code>in.nextInt()</code>. When I choose the cave, the messages pop up at 2-second intervals, and then as soon as it gets past that part, it gives me the error:</p>\n\n<pre><code>Exception in thread \"main\" java.util.NoSuchElementException: No line found\n    at java.util.Scanner.nextLine(Unknown Source)\n    at Dragon.main(Dragon.java:81)\n</code></pre>\n\n<p>I have tried <code>hasNextLine()</code> and <code>hasNextInt()</code>, and when I use <code>while hasNextLine()</code> in the <code>main</code> method, I get a ton more errors. When I use <code>while hasNextInt()</code> in the <code>chooseCave()</code> method, it doesn't accept my input.</p>\n\n<p>When I use <code>if hasNextInt()</code> in the <code>chooseCave()</code> method, it doesn't accept my input for the <code>playAgain</code> string, and goes straight into another game, but then the <code>hasNextInt()</code> boolean returns <code>false</code> and it spams \"Which cave...\" infinitely.</p>\n\n<p>I've gone through the error reports and the Java-docs and Stack Overflow's with similar problems. Please help.</p>\n\n<pre><code>import java.util.Scanner;\npublic class Dragon {\n\npublic static void displayIntro() {\n    System.out.println(\"You are in a land full of dragons. In front of you, \");\n    System.out.println(\"You see two caves. In one cave, the dragon is friendly\");\n    System.out.println(\"and will share his treasure with you. The other dragon\");\n    System.out.println(\"is greedy and hungry, and will eat you on sight\");\n    System.out.println(' ');\n}\n\npublic static int chooseCave() {\n    Scanner in = new Scanner(System.in);\n    int cave = 0;\n    while (cave != 1 &amp;&amp; cave != 2) {\n        System.out.println(\"Which cave will you go into? (1 or 2)\");\n\n        cave = in.nextInt();\n\n    }\n    in.close();\n    return cave;\n} \n\npublic static void checkCave(int chosenCave) {\n    System.out.println(\"You approach the cave...\");\n    try\n       {\n       // Sleep at least n milliseconds.\n       // 1 millisecond = 1/1000 of a second.\n       Thread.sleep( 2000 );\n       }\n    catch ( InterruptedException e )\n       {\n       System.out.println( \"awakened prematurely\" );\n       }\n    System.out.println(\"It is dark and spooky...\");\n    try\n       {\n       // Sleep at least n milliseconds.\n       // 1 millisecond = 1/1000 of a second.\n       Thread.sleep( 2000 );\n       }\n    catch ( InterruptedException e )\n       {\n       System.out.println( \"awakened prematurely\" );\n       }\n    System.out.println(\"A large dragon jumps out in front of you! He opens his jaws and...\");\n    try\n       {\n       // Sleep at least n milliseconds.\n       // 1 millisecond = 1/1000 of a second.\n       Thread.sleep( 2000 );\n       }\n    catch ( InterruptedException e )\n       {\n       System.out.println( \"awakened prematurely\" );\n       }\n\n    double friendlyCave = Math.ceil(Math.random() * 2);\n\n    if (chosenCave == friendlyCave) {\n        System.out.println(\"Gives you his treasure!\");\n    }\n    else {\n        System.out.println(\"Gobbles you down in one bite!\");\n    }\n\n\n\n}\npublic static void main(String[] args) {\n    Scanner inner = new Scanner(System.in);\n    String playAgain = \"yes\";\n    boolean play = true;\n    while (play) {\n        displayIntro();\n        int caveNumber = chooseCave();\n        checkCave(caveNumber);\n        System.out.println(\"Do you want to play again? (yes or no)\");\n        playAgain = inner.nextLine();\n        if (playAgain == \"yes\") {\n            play = true;\n        }\n        else {\n            play = false;\n        }\n    }\n    inner.close();\n\n}\n\n}\n</code></pre>\n","question_id":15398703,"tags":["java","exception","java.util.scanner"],"score":16,"accepted_answer_id":15398862,"is_answered":true,"view_count":208761,"last_edit_date":1363221839},{"owner":{"profile_image":"https://www.gravatar.com/avatar/bcdff3f230bd68f245c024dbb7b509e4?s=256&d=identicon&r=PG","account_id":37161,"user_type":"registered","user_id":106189,"link":"https://stackoverflow.com/users/106189/jim-hurne","reputation":7215,"display_name":"Jim Hurne","accept_rate":89},"content_license":"CC BY-SA 3.0","link":"https://stackoverflow.com/questions/2792728/when-is-it-appropriate-to-use-error-codes","last_activity_date":1636464598,"creation_date":1273286066,"answer_count":11,"title":"When is it appropriate to use error codes?","body":"<p>In languages that support exception objects (Java, C#), when is it appropriate to use <a href=\"http://en.wikipedia.org/wiki/Error_code\" rel=\"noreferrer\">error codes</a>? Is the use of error codes ever appropriate in typical enterprise applications?</p>\n\n<p>Many well-known software systems employ error codes (and a corresponding error code reference). Some examples include operating systems (Windows), databases (Oracle, DB2), and middle-ware products (WebLogic, WebSphere). What benefits do error codes provide? What are the disadvantages to using error codes?</p>\n","question_id":2792728,"tags":["c#","java","exception","error-handling","error-code"],"score":27,"accepted_answer_id":2792895,"is_answered":true,"view_count":5558,"last_edit_date":1316088046},{"owner":{"profile_image":"https://www.gravatar.com/avatar/f7cf53bd8e67338b36d086f48477edfa?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":22531657,"user_type":"registered","user_id":16723586,"link":"https://stackoverflow.com/users/16723586/kiznet007","reputation":15,"display_name":"Kiznet007"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/69892732/catching-an-exception-when-a-user-inputs-an-integer-while-using-a-scanner-object","last_activity_date":1636438949,"creation_date":1636430962,"answer_count":1,"title":"Catching an exception when a user inputs an integer while using a Scanner object","body":"<p>I'm trying to catch an exception when the user enters any integer in the Scanner. I understand that using a String item = scan.nextLine() will allow for any input to be made including integers. I created a custom exception to catch the number 1. But what happens if the user inputs 999 or any other integer. How can I catch those other integers as part of the exception?</p>\n<p>import java.util.Scanner;\nimport java.lang.Exception;</p>\n<p>public class ExampleOne {</p>\n<pre><code>public static void main(String[] args) throws TestCustomException {\n    \n    System.out.println(&quot;Please enter any word:&quot;);\n    \n    try {\n        \n        Scanner scan = new Scanner(System.in);\n        String item = scan.nextLine();\n        if (item.contains(&quot;1&quot;)) {\n            throw new TestCustomException();\n        } \n    }catch (TestCustomException e) {\n        System.out.println(&quot;A problem occured:  &quot; + e);\n    }\n    \n    System.out.println(&quot;Thank you for using my application.&quot;);\n    \n}\n</code></pre>\n<p>}</p>\n<p>public class TestCustomException extends Exception {</p>\n<pre><code>TestCustomException (){\n    super(&quot;You can't enter any number value here&quot;);\n}\n</code></pre>\n<p>}</p>\n","question_id":69892732,"tags":["java","string","exception","input","integer"],"score":0,"accepted_answer_id":69893623,"is_answered":true,"view_count":409},{"owner":{"profile_image":"https://www.gravatar.com/avatar/2b39a4a337cd772a45c78706b173313d?s=256&d=identicon&r=PG","account_id":174942,"user_type":"registered","user_id":404608,"link":"https://stackoverflow.com/users/404608/magggi","reputation":1145,"display_name":"Magggi","accept_rate":14},"content_license":"CC BY-SA 2.5","link":"https://stackoverflow.com/questions/3625672/java-exception-handling","last_activity_date":1620299882,"creation_date":1283418876,"answer_count":8,"title":"Java exception handling","body":"<p>How do I use exceptions and exception handling to make my program continue even if an exception occurs while processing certain files in a set of files?</p>\n\n<p>I want my program to work fine for correct files while for those files which cause an exception in program, it should ignore.</p>\n\n<p>Regards,</p>\n\n<p>magggi</p>\n","question_id":3625672,"tags":["java","exception"],"score":7,"accepted_answer_id":3625721,"is_answered":true,"view_count":12012,"last_edit_date":1283419729},{"owner":{"profile_image":"https://i.stack.imgur.com/yVhlW.jpg?s=256&g=1","account_id":10108030,"user_type":"registered","user_id":7469973,"link":"https://stackoverflow.com/users/7469973/numan-gillani","reputation":499,"display_name":"Numan Gillani"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/51606891/how-to-set-icon-to-the-alert-dialog-programatically-in-android","last_activity_date":1620290564,"creation_date":1533019176,"answer_count":4,"title":"How to set Icon to the Alert Dialog Programatically in Android","body":"<p>Em using these statements for creating an Alert Dialog and set icon to it,</p>\n<pre><code>       AlertDialog.Builder builder = new AlertDialog.Builder(this);\n\n       builder.setIcon(this.getDrawable(R.drawable.video_downloader));\n\n       builder.setTitle(&quot;Congratulations !!!&quot;);\n\n       builder.show();\n</code></pre>\n<p>But it is crashing at setIcon, when I checked in drawable folder, the video_downloader icon is there already.</p>\n<pre><code>AndroidRuntime: FATAL EXCEPTION: main\njava.lang.IllegalStateException: Could not execute method of the activity\n    at android.view.View$1.onClick(View.java:3607)\n    at android.view.View.performClick(View.java:4212)\n    at android.view.View$PerformClick.run(View.java:17476)\n    at android.os.Handler.handleCallback(Handler.java:800)\n    at android.os.Handler.dispatchMessage(Handler.java:100)\n    at android.os.Looper.loop(Looper.java:194)\n    at android.app.ActivityThread.main(ActivityThread.java:5371)\n    at java.lang.reflect.Method.invokeNative(Native Method)\n    at java.lang.reflect.Method.invoke(Method.java:525)\n    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)\n    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)\n    at dalvik.system.NativeStart.main(Native Method)\n Caused by: java.lang.reflect.InvocationTargetException\n    at java.lang.reflect.Method.invokeNative(Native Method)\n    at java.lang.reflect.Method.invoke(Method.java:525)\n    at android.view.View$1.onClick(View.java:3602)\n    at android.view.View.performClick(View.java:4212) \n    at android.view.View$PerformClick.run(View.java:17476) \n    at android.os.Handler.handleCallback(Handler.java:800) \n    at android.os.Handler.dispatchMessage(Handler.java:100) \n    at android.os.Looper.loop(Looper.java:194) \n    at android.app.ActivityThread.main(ActivityThread.java:5371) \n    at java.lang.reflect.Method.invokeNative(Native Method) \n    at java.lang.reflect.Method.invoke(Method.java:525) \n    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) \n    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) \n    at dalvik.system.NativeStart.main(Native Method) \n Caused by: **java.lang.NoSuchMethodError**: numan.downloader.Test.Front.getDrawable\n    at numan.downloader.Test.Front.GetMedia(Front.java:115)\n    at java.lang.reflect.Method.invokeNative(Native Method) \n    at java.lang.reflect.Method.invoke(Method.java:525) \n    at android.view.View$1.onClick(View.java:3602) \n    at android.view.View.performClick(View.java:4212) \n    at android.view.View$PerformClick.run(View.java:17476) \n    at android.os.Handler.handleCallback(Handler.java:800) \n    at android.os.Handler.dispatchMessage(Handler.java:100) \n    at android.os.Looper.loop(Looper.java:194) \n    at android.app.ActivityThread.main(ActivityThread.java:5371) \n    at java.lang.reflect.Method.invokeNative(Native Method) \n    at java.lang.reflect.Method.invoke(Method.java:525) \n    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) \n    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) \n    at dalvik.system.NativeStart.main(Native Method) \n</code></pre>\n<p>07-31 08:35:51.291 500-519/? E/AppErrorDialog: Failed to get ILowStorageHandle instance</p>\n","question_id":51606891,"tags":["java","android","exception","android-alertdialog","nosuchmethoderror"],"score":-1,"accepted_answer_id":51606936,"is_answered":true,"view_count":4635,"last_edit_date":1620290564},{"owner":{"profile_image":"https://graph.facebook.com/10159420994469363/picture?type=large","account_id":19934003,"user_type":"registered","user_id":14607078,"link":"https://stackoverflow.com/users/14607078/tom-ronaldo","reputation":21,"display_name":"Tom Ronaldo"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/67412378/handle-scanner-exception-on-java-program","last_activity_date":1620280407,"creation_date":1620279127,"answer_count":0,"title":"Handle Scanner exception on Java program","body":"<p>I am working on a school project. I have all the functionality working but when I submit the project through Mimir, during deposits and withdraws it gives the following error:</p>\n<pre><code>Enter the amount you want to Deposit :$Exception in thread &quot;main&quot; java.util.NoSuchElementException\n\n13 at java.util.Scanner.throwFor(Scanner.java:862)\n14 at java.util.Scanner.next(Scanner.java:1485)\n15 at java.util.Scanner.nextDouble(Scanner.java:2345)\n16 at BankAccount.deposit(BankAccount.java:24)\n17 at SavingsAccountDemo.main(SavingsAccountDemo.java:30)\n</code></pre>\n<p>The project does says the following: Please make sure that your classes throw appropriate exceptions when an attempt is made to insert invalid data.</p>\n<p>I tried to add the try and catch with <code>java.util.InputMismatchException e</code> but it doesn't seem to be fixing it. I think it's because the userInput is a double and they are entering something different. Any ideas how can I fix that? Here is the code:</p>\n<pre><code>///SavingsAccountDemo class\nimport java.util.*;\npublic class SavingsAccountDemo {\n    \n    public static void main(String[] args) {\n        \n        Scanner keyboard = new Scanner(System.in);\n        \n        double startingBalance;\n        double interestRate;\n        String userInput;\n                \n        System.out.print(&quot;Enter beginning balance :$&quot;);\n        startingBalance = keyboard.nextDouble();\n        \n        System.out.print(&quot;Enter interest rate(whole number) :%&quot;);\n        interestRate = keyboard.nextDouble();\n        \n        double bal = startingBalance;\n        double rate = interestRate;\n        \n        BankAccount ba = new BankAccount(startingBalance, interestRate);\n        BankDemo sv = new BankDemo(bal, rate);\n        \n        while(startingBalance &gt; -1) {\n            try {\n                System.out.println(&quot;Enter D for deposit&quot; + &quot;\\nEnter W to Withdraw&quot; + &quot;\\nEnter B for Balance&quot; + \n                                    &quot;\\nEnter M for Monthly Process&quot; + &quot;\\nEnter E to Exit&quot;);\n                userInput = keyboard.next().toLowerCase();\n                \n                if(&quot;d&quot;.equals(userInput)) {\n                    ba.deposit();\n                } else if(&quot;w&quot;.equals(userInput)) {\n                    ba.withdraw();\n                } else if(&quot;b&quot;.equals(userInput)) {\n                    ba.totalBalance();\n                } else if(&quot;m&quot;.equals(userInput)) {\n                    ba.monthlyProcess();\n                } else if(&quot;e&quot;.equals(userInput)) {\n                    ba.exit();\n                    break;\n                }\n                else {\n                    System.out.print(&quot;Error, option not valid\\n&quot;);\n                }\n            }\n            catch (java.util.InputMismatchException e) {\n                System.out.print(&quot;Error&quot;);\n            }\n        }\n    }\n\n}\n///BankAccount class\nimport java.util.*;\npublic class BankAccount {\n    protected double balance;\n    protected double numDeposits;\n    protected double numWithdrawals;\n    protected double annualRate;\n    protected double monthlyServCharg;\n    protected boolean active;\n    \n    Scanner keyboard = new Scanner(System.in);\n    \n    public BankAccount(double startingBalance, double interestRate) {\n        balance = startingBalance;\n        annualRate = interestRate /= 100.0;\n        if(balance &lt; 25) {\n            active = false;\n        } else\n            active = true;\n    }\n    public void deposit() {\n        try {\n        double valueD;\n        \n        System.out.print(&quot;Enter the amount you want to Deposit :$&quot;);\n        valueD = keyboard.nextDouble();\n        if(valueD &lt; 0) {\n            System.out.println(&quot;Error: Must enter positive value\\n&quot;);\n        }\n        if( balance + valueD &gt;= 25 &amp;&amp; !active) {\n            System.out.print(&quot;Your account is now ACTIVE\\n&quot;);\n            active = true;      \n        }\n        balance += valueD;\n        numDeposits++;\n        } \n        catch (java.util.InputMismatchException e){\n            keyboard.nextLine();\n        }\n    }\n    public void withdraw() {\n        try {\n            double valueW;\n            \n            System.out.print(&quot;Enter the amount you want to withdraw :$&quot;);\n            valueW = keyboard.nextDouble();\n            if(valueW &lt; 0) {\n                System.out.println(&quot;Error: Must enter positive value\\n&quot;);\n            }\n            balance -= valueW;\n            numWithdrawals++;\n            if(balance &lt; 0) {\n                System.out.print(&quot;ERROR: Transaction declined!! This transaction will cause overdraft or zero balance\\n&quot;);\n                balance += valueW;\n            } else if(balance &lt;= 25 &amp;&amp; active) {\n                System.out.print(&quot;Your balance is less than minimum balance. Your account is now INACTIVE\\n&quot;);\n                active = false;\n                }\n            if(numWithdrawals &gt; 4) {\n                balance --;\n                System.out.print(&quot;You have exceeded monthly limit of withdrawals. Fee of $1 charged\\n&quot;);\n            }\n        } \n        catch (java.util.InputMismatchException e) {\n            keyboard.nextLine();\n        }\n        \n    }\n    public void totalBalance() {\n        System.out.printf(&quot;Your Balance is: %.2f\\n&quot;, balance);\n    }\n    public void calcInterest() {\n        double monRate = annualRate / 12;\n        double monInt = balance * monRate;\n        balance += monInt;\n    }\n    public void monthlyProcess() {\n        calcInterest();\n        balance -= monthlyServCharg;\n        numWithdrawals = 0;\n        numDeposits = 0;\n        monthlyServCharg = 0;\n        System.out.printf(&quot;Your Balance after Monthly process is: %.2f\\n&quot;, balance);\n    }\n    \n    public void exit() {\n        totalBalance();\n        System.out.print(&quot;Thank you. Bye&quot;);\n    }\n}\n</code></pre>\n","question_id":67412378,"tags":["java","exception","java.util.scanner"],"score":0,"is_answered":false,"view_count":55,"last_edit_date":1620280407},{"owner":{"profile_image":"https://www.gravatar.com/avatar/00a87df6ac471bb0b3f6c52ae17f5ae2?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":19184838,"user_type":"registered","user_id":14015832,"link":"https://stackoverflow.com/users/14015832/bayraktarmd","reputation":3,"display_name":"bayraktarmd"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/67408280/my-fixture-algorithm-throws-exception-when-there-are-odd-team-numbers","last_activity_date":1620249379,"creation_date":1620246162,"answer_count":1,"title":"My fixture algorithm throws exception when there are odd team numbers","body":"<p>My fixture generator algorithm throws java.lang.IndexOutOfBoundsException when the team list count is odd. I'm sending 21 sized team list and gives this exception. And throws the same exception even when it's 17, 19, 23. Here is the exception:</p>\n<pre><code>E/AndroidRuntime: FATAL EXCEPTION: main\nProcess: com.xelorium.soccerleaguetable, PID: 1189\njava.lang.IndexOutOfBoundsException: Index: 21, Size: 21\n    at java.util.LinkedList.checkElementIndex(LinkedList.java:555)\n    at java.util.LinkedList.get(LinkedList.java:476)\n    at com.xelorium.soccerleaguetable.FixtureGenerator.getFixtures(FixtureGenerator.java:34)\n</code></pre>\n<p>FixtureGenerator.java:</p>\n<pre><code>public class FixtureGenerator&lt;T extends Object&gt; {\n\npublic List&lt;List&lt;MatchModel&lt;T&gt;&gt;&gt; getFixtures(List&lt;T&gt; teams, boolean includeReverseFixtures) {\n\n    int numberOfTeams = teams.size();\n\n    boolean ghost = false;\n    if (numberOfTeams % 2 != 0) {\n        numberOfTeams++;\n        ghost = true;\n    }\n\n    int totalRounds = numberOfTeams - 1;\n    int matchesPerRound = numberOfTeams / 2;\n    List&lt;List&lt;MatchModel&lt;T&gt;&gt;&gt; rounds = new LinkedList&lt;List&lt;MatchModel&lt;T&gt;&gt;&gt;();\n\n    for (int round = 0; round &lt; totalRounds; round++) {\n        List&lt;MatchModel&lt;T&gt;&gt; fixtures = new LinkedList&lt;MatchModel&lt;T&gt;&gt;();\n        for (int match = 0; match &lt; matchesPerRound; match++) {\n            int home = (round + match) % (numberOfTeams - 1);\n            int away = (numberOfTeams - 1 - match + round) % (numberOfTeams - 1);\n\n            if (match == 0) {\n                away = numberOfTeams - 1;\n            }\n            //Here where it throws the exception\n            fixtures.add(new MatchModel&lt;T&gt;(teams.get(home), teams.get(away)));\n        }\n        rounds.add(fixtures);\n    }\n</code></pre>\n","question_id":67408280,"tags":["java","algorithm","exception","fixtures"],"score":-1,"accepted_answer_id":67408762,"is_answered":true,"view_count":80},{"owner":{"user_type":"does_not_exist","display_name":"user15613889"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/67402595/unsatisfieddependencyexception-with-rest-service","last_activity_date":1620242811,"creation_date":1620222424,"answer_count":0,"title":"UnsatisfiedDependencyException with REST service","body":"<p>I am trying to create some unit tests for my REST API service class. This service class implements a service interface. However, when I try to run my tests I get this error:</p>\n<blockquote>\n<p>org.springFramework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dev.x.y.unit.ContactServiceImplTest': Unsatisfied dependency expressed through field 'contactServiceImpl';</p>\n</blockquote>\n<p>My test class:</p>\n<pre><code>@ExtendWith(SpringExtension.class)\nclass ContactServiceImplTest {\n\n@MockBean\nprivate ContactRepository contactRepository;\n\n@Autowired\nprivate ContactServiceImpl contactServiceImpl;\n...\n</code></pre>\n<p>my contactServiceImpl implements from my ContactService, I have tried annotating with @Component and @Service, but I am still receiving the same error.</p>\n<p>ContactServiceImpl class:</p>\n<pre><code>@Service\n@Transactional\npublic class ContactServiceImpl implements ContactService {\n\nLogger logger = LoggerFactory.getLogger(ContactServiceImpl.class);\n\n@Autowired\nprivate final ContactRepository contactRepository;\n....\n</code></pre>\n<p>My interface:</p>\n<pre><code>@Service\npublic interface ContactService { ... }\n</code></pre>\n<p>Any advice would be amazing.</p>\n","question_id":67402595,"tags":["java","spring-boot","exception"],"score":0,"is_answered":false,"view_count":194,"last_edit_date":1620242811},{"owner":{"profile_image":"https://lh4.googleusercontent.com/-bJ9jv_1cz3s/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3reGJuhQYXII5V4i830X3pOPBeNVhw/photo.jpg?sz=256","account_id":16816125,"user_type":"registered","user_id":12157888,"link":"https://stackoverflow.com/users/12157888/sheharyar-lodhi","reputation":1,"display_name":"Sheharyar Lodhi"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/67404990/dexguard-release-build-throws-error-java-lang-unsatisfiedlinkerror-dlopen-fail","last_activity_date":1620232040,"creation_date":1620231183,"answer_count":1,"title":"Dexguard release build throws error: java.lang.UnsatisfiedLinkError: dlopen failed: library &quot;libsuprema_libusb.so&quot; not found","body":"<p>I am trying to make dexguard release build having libraries .so files so when I attach the debugger</p>\n<p>adb logcat throws exception:</p>\n<p>java.lang.UnsatisfiedLinkError: dlopen failed: library &quot;libsuprema_libusb.so&quot; not found</p>\n<p>Please any one guide as i am using suprema slim2 biometric scanner and everything works great in simple release but when i make release protected build than face this issue</p>\n","question_id":67404990,"tags":["java","android","exception",".so","dexguard"],"score":0,"is_answered":false,"view_count":220},{"owner":{"profile_image":"https://i.stack.imgur.com/09bUc.jpg?s=256&g=1","account_id":6537227,"user_type":"registered","user_id":5056288,"link":"https://stackoverflow.com/users/5056288/phanik","reputation":21,"display_name":"Phanik"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/67400314/how-to-split-string-by-reading-text-from-file","last_activity_date":1620216209,"creation_date":1620213740,"answer_count":3,"title":"how to split string by reading text from file","body":"<p>I am trying to read os-release file on Linux and trying to get the OS version by finding VERSION_ID=&quot;12.3&quot; line. I wrote below piece of code but at the last after splitting the string first time I am unable to go further. I reached up to splitting to &quot;12.3&quot; from VERSION_ID, after this I applied split function again and getting &quot;java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0&quot; error. , Need your help and valuable suggestions.</p>\n<pre><code>File fobj2 = new File(&quot;C:\\\\os-release&quot;);\nif(fobj2.exists() &amp;&amp; !fobj2.isDirectory())\n{\nScanner sc = new Scanner(fobj2);\nwhile(sc.hasNextLine())\n    {\n     String line = sc.nextLine();\n     //VERSION_ID=&quot;12.3&quot;\n     if(line.contains(&quot;VERSION_ID=&quot;))\n     {\n     System.out.println(&quot; VERSION_ID= &quot; + line );\n     String [] ver = line.split(&quot;=&quot;);\n     if(ver.length &gt; 1)\n     {\n         String [] ver_id = line.split(&quot;=&quot;);\n         System.out.println(&quot; ver_id.length &quot; + ver_id.length );\n         System.out.println(&quot; ver_id[0] &quot; + ver_id[0] );\n         System.out.println(&quot; ver_id[1] &quot; + ver_id[1] );\n         System.out.println(&quot; ver_id[1].length() &quot; + ver_id[1].length() );\n                     \n         String [] FinalVer1 = ver_id[1].split(&quot;.&quot;);\n\n         System.out.println(&quot; FinalVer1[1].length() &quot; + FinalVer1[1].length() );\n         System.out.println(&quot; FinalVer1[1] &quot; + FinalVer1[1] );\n     }\n     }                   \n}\n</code></pre>\n","question_id":67400314,"tags":["java","arrays","string","exception","split"],"score":0,"accepted_answer_id":67400921,"is_answered":true,"view_count":68},{"owner":{"profile_image":"https://www.gravatar.com/avatar/89d5fbaa2c35bf567d07b78af8ecd998?s=256&d=identicon&r=PG","account_id":2338912,"user_type":"registered","user_id":2050642,"link":"https://stackoverflow.com/users/2050642/user2050642","reputation":11,"display_name":"user2050642"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/14751256/how-to-pass-exceptions-globally-to-a-single-action-from-other-actions-in-struts","last_activity_date":1620184874,"creation_date":1360240483,"answer_count":1,"title":"How to pass exceptions globally to a single action from other actions in Struts 2","body":"<p>I want to pass exceptions globally to a single action file called <code>ErrorAction</code>, say from <code>Index</code> action.</p>\n<p><strong>Here's my <code>struts.xml</code> file:</strong></p>\n<pre class=\"lang-xml prettyprint-override\"><code>&lt;global-results&gt;    \n    &lt;result name=&quot;myErrorHandler&quot; type=&quot;redirectAction&quot;&gt;    \n        &lt;param name=&quot;actionName&quot;&gt;myError&lt;/param&gt;\n    &lt;/result&gt;    \n    &lt;result name=&quot;login&quot; type=&quot;tiles&quot;&gt;\n        login\n    &lt;/result&gt;    \n&lt;/global-results&gt;    \n\n&lt;global-exception-mappings&gt;    \n    &lt;exception-mapping exception=&quot;java.lang.Exception&quot; result=&quot;myErrorHandler&quot; /&gt;    \n&lt;/global-exception-mappings&gt;    \n\n&lt;action name=&quot;myError&quot; class=&quot;com.actions.ErrorAction&quot;&gt;    \n    &lt;interceptor-ref name=&quot;exception&quot; /&gt;    \n    &lt;interceptor-ref name=&quot;defaultStack&quot; /&gt;    \n    &lt;result name=&quot;error&quot; type=&quot;tiles&quot;&gt;error&lt;/result&gt;    \n&lt;/action&gt;   \n\n....    \n\n&lt;action name=&quot;Index&quot; class=&quot;com.actions.Index&quot;&gt;    \n    &lt;interceptor-ref name=&quot;defaultStack&quot; /&gt;    \n    &lt;result name=&quot;success&quot; type=&quot;tiles&quot;&gt;home&lt;/result&gt;    \n&lt;/action&gt;\n</code></pre>\n","question_id":14751256,"tags":["java","exception","struts2","xml-configuration","interceptorstack"],"score":1,"is_answered":false,"view_count":418,"last_edit_date":1617773655},{"owner":{"profile_image":"https://i.stack.imgur.com/MjbfY.jpg?s=256&g=1","account_id":5465673,"user_type":"registered","user_id":4346563,"link":"https://stackoverflow.com/users/4346563/iitrainii","reputation":11,"display_name":"iitrainii"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/67387023/how-to-unit-test-the-json-exception-and-hit-cover-the-catch-block","last_activity_date":1620139828,"creation_date":1620139501,"answer_count":1,"title":"How to unit test the JSON exception and hit/cover the catch block","body":"<p>Here is a snippet of the code I am trying to cover, specifically the catch block.</p>\n<pre><code>JSONObject bodyObject = new JSONObject();\nString body = null;\n\ntry{\n   body = bodyObject.put(DecisionTreeConstants.EDGE_ACCOUNT_STATUS, processStatusPretty).toString();\n} catch (JSONException e) {\n   LOGGER.debug(&quot; &quot;);\n}\n</code></pre>\n","question_id":67387023,"tags":["java","json","exception","junit","code-coverage"],"score":-1,"is_answered":false,"view_count":157},{"owner":{"profile_image":"https://www.gravatar.com/avatar/65cda677975b95a5e78c4ee663c08b19?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":12019463,"user_type":"registered","user_id":8793412,"link":"https://stackoverflow.com/users/8793412/karthikeyan","reputation":1937,"display_name":"Karthikeyan","accept_rate":88},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/67371571/code-terminated-once-exception-caught-java","last_activity_date":1620057484,"creation_date":1620055502,"answer_count":3,"title":"code terminated once exception caught java","body":"<p>I was expecting remaining code to continue even after throwing exception for some products. Please find my code below.</p>\n<pre><code>public class Example1 {\n\n    void productCheck(int[] weight) throws InvalidProductException {\n\n        for (int i = 0; i &lt; weight.length; i++) {\n            System.out.println(&quot;Product --&gt;&quot;+weight[i]);\n            if (weight[i] &lt; 100) {\n                System.out.println(&quot;Product exception--&gt;&quot;+weight[i]);\n                throw new InvalidProductException(&quot;Product Invalid&quot;);\n            }\n        }\n\n    }\n\n    public static void main(String args[]) {\n        Example1 obj = new Example1();\n        \n        int[] weight = {110, 60, 10, 20, 100, 60 };\n        try {\n            obj.productCheck(weight);\n            \n        } catch (InvalidProductException ex) {\n            System.out.println(&quot;Caught the exception for Product&quot;);\n            System.out.println(ex.getMessage());\n        } \n    }\n\n}\n\npublic class InvalidProductException extends Exception\n    {\npublic InvalidProductException(String s)\n    {\n    // Call constructor of parent Exception\n    super(s);\n    }\n}\n</code></pre>\n<p>Output :</p>\n<pre><code>Product --&gt;110\nProduct --&gt;60\nProduct exception--&gt;60\nCaught the exception for Product\nProduct Invalid\n</code></pre>\n","question_id":67371571,"tags":["java","exception"],"score":-1,"accepted_answer_id":67371946,"is_answered":true,"view_count":95},{"owner":{"profile_image":"https://lh4.googleusercontent.com/-UqGqwXzwLbs/AAAAAAAAAAI/AAAAAAAACME/OdYv56wfiFg/photo.jpg?sz=256","account_id":9268266,"user_type":"registered","user_id":6883108,"link":"https://stackoverflow.com/users/6883108/shailesh-jain","reputation":43,"display_name":"Shailesh Jain","accept_rate":25},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/39706771/how-can-i-get-parameters-name-same-as-a-parameter-in-java","last_activity_date":1617643718,"creation_date":1474903772,"answer_count":2,"title":"How can I get parameters name same as a parameter in java","body":"<pre><code>public void parametersForValidation(String name,String address){\nvalidateParameters(name,address);\n}\n\nprivate void validateParameters(Object... values){\nfor(Object value:values){\nObjects.requirNonNull(value,&quot;Value is mandatory&quot;);\n}\n}\n</code></pre>\n<p>I want instead of &quot;value is mandatory&quot;, parameter name like &quot;Name is namdatory&quot; and &quot;address is mandatory&quot; should come.</p>\n","question_id":39706771,"tags":["java","reflection"],"score":-1,"is_answered":false,"view_count":1176,"last_edit_date":1617643718},{"owner":{"profile_image":"https://lh3.googleusercontent.com/-Z3JeceGBmgc/AAAAAAAAAAI/AAAAAAAABk0/asNh0EI4Y9I/photo.jpg?sz=256","account_id":6472137,"user_type":"registered","user_id":5903601,"link":"https://stackoverflow.com/users/5903601/ankush-kapoor","reputation":495,"display_name":"Ankush Kapoor","accept_rate":40},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/66950757/how-to-invoke-kotlin-object-method-using-reflection-in-java","last_activity_date":1617615885,"creation_date":1617614575,"answer_count":2,"title":"How to invoke Kotlin object method using reflection in Java?","body":"<p>I want to invoke setApiHelper method in the below code using java reflection. How can I do so?</p>\n<pre><code>object PlayerUtils {\n    private var apiHelper: String? = null\n    fun setApiHelper(apiHelper: String) {\n        this.apiHelper = apiHelper\n        println(apiHelper)\n    }\n\n    fun getApiHelper(): String? {\n        return this.apiHelper\n    }\n}\n</code></pre>\n<p><strong>My Implementation</strong></p>\n<pre><code>private static void testingPlayerUtils() {\n        try {\n            Class&lt;?&gt; cls = Class.forName(&quot;reflection.PlayerUtils&quot;);\n            cls.newInstance();\n            Method method = cls.getDeclaredMethod(&quot;setApiHelper&quot;);\n            method.invoke(cls.newInstance(), &quot;TESTING&quot;);\n        } catch (ClassNotFoundException | NoSuchMethodException e) {\n            e.printStackTrace();\n        } catch (IllegalAccessException e) {\n            e.printStackTrace();\n        } catch (InstantiationException e) {\n            e.printStackTrace();\n        } catch (InvocationTargetException e) {\n            e.printStackTrace();\n        }\n    }\n</code></pre>\n<p>this gives an error</p>\n<pre><code>java.lang.IllegalAccessException: Class TestingReflection2 can not access a member of class reflection.PlayerUtils with modifiers &quot;private&quot;\n    at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)\n    at java.lang.Class.newInstance(Class.java:436)\n    at TestingReflection2.testingPlayerUtils(TestingReflection2.java:20)\n    at TestingReflection2.main(TestingReflection2.java:14)\n</code></pre>\n","question_id":66950757,"tags":["java","android","kotlin","reflection"],"score":1,"accepted_answer_id":66951034,"is_answered":true,"view_count":2072},{"owner":{"profile_image":"https://www.gravatar.com/avatar/c8df6a60fa19ec03cde467dad65c8f24?s=256&d=identicon&r=PG","account_id":29845,"user_type":"registered","user_id":80932,"link":"https://stackoverflow.com/users/80932/ufk","reputation":31302,"display_name":"ufk","accept_rate":85},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/2126714/get-all-variable-names-in-a-class","last_activity_date":1617450933,"creation_date":1264329513,"answer_count":4,"title":"Get all variable names in a class","body":"<p>I have a class and I want to find all of its <em>public fields</em> (not methods). How can I do this?</p>\n","question_id":2126714,"tags":["java","reflection"],"score":108,"accepted_answer_id":2126722,"is_answered":true,"view_count":173404,"last_edit_date":1617450933},{"owner":{"profile_image":"https://lh3.googleusercontent.com/-6G595h39MTQ/AAAAAAAAAAI/AAAAAAAAAAA/AKxrwcbj5poKQQOimWOLEZmoXJxqTxKAkg/mo/photo.jpg?sz=256","account_id":15099616,"user_type":"registered","user_id":10897032,"link":"https://stackoverflow.com/users/10897032/michael-hozza","reputation":47,"display_name":"Michael Hozza"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/66925088/java-chained-reflection","last_activity_date":1617443364,"creation_date":1617396503,"answer_count":1,"title":"Java chained reflection","body":"<p>I have this chained method call</p>\n<p>Integer.parseInt(A.get().getC().getD().toString());</p>\n<p>I need to make this with reflection. I know that I can use Class.forName(String class) and then invoke methods, but how do I save method results so I can call that chain.</p>\n<p>Classes:</p>\n<pre><code>public class A\n{\n       public static B get() { return new B(); }\n}\n\npublic class B\n{\n     public C getC() { return new C();}\n}\n\npublic class C\n{\n      public C getD() { return new D();}\n}\n</code></pre>\n","question_id":66925088,"tags":["java","reflection"],"score":2,"accepted_answer_id":66925204,"is_answered":true,"view_count":215},{"owner":{"profile_image":"https://www.gravatar.com/avatar/8814ddf38903764241e1e6b1f6d7212e?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":4490443,"user_type":"registered","user_id":3651664,"link":"https://stackoverflow.com/users/3651664/highpredator","reputation":790,"display_name":"HighPredator","accept_rate":91},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/66918458/unexpected-exception-for-remote-running-unit-tests-with-methodhandles","last_activity_date":1617362006,"creation_date":1617362006,"answer_count":0,"title":"Unexpected exception for remote running unit tests with MethodHandles","body":"<p>The following line of code in tests</p>\n<pre><code>var lookup = MethodHandles.privateLookupIn(Field.class, MethodHandles.lookup());\n</code></pre>\n<p>where Field is java.lang.reflect.Field\nthrows a</p>\n<pre><code>java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @497470ed\n    at java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:260) ~[?:?] \n</code></pre>\n<p>The code works fine if tests are run locally (either via IDE or maven lifecycle), but fails on maven test run on CI pipeline on a remote host.</p>\n<p>Maven is configured for java 11, but test execution as we saw in logs was using openjdk-16 jvm.</p>\n<p>Would appreciate any ideas on where to look.</p>\n","question_id":66918458,"tags":["java","maven","reflection"],"score":0,"is_answered":false,"view_count":157},{"owner":{"profile_image":"https://www.gravatar.com/avatar/8aae693dd9b2784d0d0618707e0284c7?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":7014150,"user_type":"registered","user_id":5376062,"link":"https://stackoverflow.com/users/5376062/darkbit","reputation":153,"display_name":"darkbit"},"content_license":"CC BY-SA 3.0","link":"https://stackoverflow.com/questions/32783591/get-a-generic-class-field-type-with-java-reflections","last_activity_date":1617346535,"creation_date":1443188540,"answer_count":2,"title":"Get a generic class field type with Java Reflections","body":"<p>I have the following class structure:</p>\n\n<pre><code>public class GenClass&lt;T&gt; {\n    public T elem;\n}\n</code></pre>\n\n<p>I use it in the following way:</p>\n\n<pre><code>public class Test {\n    public GenClass&lt;UUID&gt; data;\n</code></pre>\n\n<p>Now I want to get the type of elem using the Field object of data(<code>Test.class.getField(\"data\")</code>)\nBut when I use <code>getType</code> to retrieve the class the Generic information is stripped away.</p>\n\n<p>How can I map the generic Information from <code>getGenericType</code> to the class object to retrieve the field with a correct type?</p>\n\n<p><strong>Edit:</strong> Since there are some misunderstandings, I try to clarify my problem.\nConsider this example:</p>\n\n<pre><code>public class AClass&lt;T, Q&gt; {\n    public Q elem;\n    // some other code using T...\n}\n\npublic class BClass&lt;T, Q&gt; {\n    public T elem;\n    // some other code using Q...\n}\n</code></pre>\n\n<p>Now I want a function to get the class of elem:</p>\n\n<pre><code>public class Test {\n    public AClass&lt;UUID, String&gt; a;\n    public BClass&lt;Integer, Float&gt; b;\n\n    void do() throws Exception {\n        Field aField = Test.class.getField(\"a\");\n        Field bField = Test.class.getField(\"b\");\n\n        getType(aField, \"elem\"); // should return String.class\n        getType(bField, \"elem\"); // should return Integer.class\n    }\n\n    Class&lt;?&gt; getType(Field f, String classField) {\n        // ???\n    } \n}\n</code></pre>\n\n<p>How did I need to implement <code>getType</code> to get my desired result?</p>\n","question_id":32783591,"tags":["java","generics","reflection"],"score":4,"is_answered":true,"view_count":4019,"last_edit_date":1443208413},{"owner":{"profile_image":"https://www.gravatar.com/avatar/bf38efdb5ea766bf988e53b7e3ca92e9?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":5218020,"user_type":"registered","user_id":4172296,"link":"https://stackoverflow.com/users/4172296/deepmindz","reputation":608,"display_name":"deepmindz","accept_rate":80},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/34190572/java-newinstance-of-generic-class","last_activity_date":1617309962,"creation_date":1449701677,"answer_count":1,"title":"Java newInstance of Generic Class","body":"<p>I am working with Java Generic classes (in this example, these are the Collection classes), and Reflection. I would like to be able to use reflection to take in a Class, check if it is an instance of a List, and then invoke the add method to it.</p>\n<p>However, I've faced some difficulties in trying to put as the parameters to invoke the method call, and getting the declared method (shown where I put-what???). Both of those method parameter calls, require an object of type  <code>Class&lt;?&gt;</code> which is the parameter type of needed for the <code>add</code> methods being invoked, which I don't know, since <code>T</code> itself is a generic.</p>\n<p>Any help is appreciated! I apologize if the question is unclear, I tried the best I could to clarify.</p>\n<pre><code>static &lt;T&gt; void TestACollection(Class&lt;T&gt; clazz) {\n     T element=clazz.newInstance();\n     if(element instanceof List&lt;?&gt;)\n     Method m=clazz.getDeclaredMethod(&quot;add&quot;, what???  ); \n     m.invoke(element, what???);\n}\n</code></pre>\n","question_id":34190572,"tags":["java","generics","reflection"],"score":0,"accepted_answer_id":34191003,"is_answered":true,"view_count":1056,"last_edit_date":1617309937},{"owner":{"profile_image":"https://www.gravatar.com/avatar/b76d0d885b3861c65ec6e30bf4d4b53b?s=256&d=identicon&r=PG","account_id":1409397,"user_type":"registered","user_id":1336310,"link":"https://stackoverflow.com/users/1336310/menno","reputation":12315,"display_name":"Menno","accept_rate":90},"content_license":"CC BY-SA 3.0","link":"https://stackoverflow.com/questions/16360632/reflection-getannotations-returns-null","last_activity_date":1617227600,"creation_date":1367589373,"answer_count":4,"title":"Reflection getAnnotations() returns null","body":"<p><strong>Searchable.java</strong></p>\n\n<pre><code>@Target(ElementType.FIELD)\n@Retention(RetentionPolicy.RUNTIME)\npublic @interface Searchable { }\n</code></pre>\n\n<p><strong>Obj.java</strong></p>\n\n<pre><code>public class Obj {\n    @Searchable\n    String myField;\n}\n</code></pre>\n\n<p><strong>void main(String[] args)</strong></p>\n\n<pre><code>Annotation[] annotations = Obj.class.getDeclaredField(\"myField\").getAnnotations();\n</code></pre>\n\n<p>I would expect <code>annotations</code> to be containing my <code>@Searchable</code>. Though it is <code>null</code>. According to documentation, this method:</p>\n\n<blockquote>\n  <p>Returns all annotations present on this element. (Returns an array of length zero if this element has no annotations.) The caller of this method is free to modify the returned array; it will have no effect on the arrays returned to other callers.</p>\n</blockquote>\n\n<p>Which is even more weird (to me), since it returns <code>null</code> instead of <code>Annotation[0]</code>.</p>\n\n<p>What am I doing wrong here and more important, how will I be able to get my <code>Annotation</code>?</p>\n","question_id":16360632,"tags":["java","reflection"],"score":13,"accepted_answer_id":16360768,"is_answered":true,"view_count":17459},{"owner":{"profile_image":"https://www.gravatar.com/avatar/bdd0c2d314fd40384bae95354b78aa3f?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":5309142,"user_type":"registered","user_id":4236078,"link":"https://stackoverflow.com/users/4236078/ale64bit","reputation":6232,"display_name":"ale64bit","accept_rate":72},"content_license":"CC BY-SA 3.0","link":"https://stackoverflow.com/questions/32539513/why-floorentry-and-other-methods-are-not-accessible-in-patriciatrie","last_activity_date":1617226468,"creation_date":1442065475,"answer_count":1,"title":"Why `floorEntry` and other methods are not accessible in PatriciaTrie?","body":"<p>While implementing an ip-lookup structure, I was trying to maintain a set of keys in a trie-like structure that allows me to search the \"floor\" of a key (that is, the largest key that is less or equal to a given key). I decided to use Apache Collections 4 <a href=\"https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/trie/PatriciaTrie.html\" rel=\"nofollow\">PatriciaTrie</a> but sadly, I found that the <a href=\"https://github.com/apache/commons-collections/blob/trunk/src/main/java/org/apache/commons/collections4/trie/AbstractPatriciaTrie.java#L1041\" rel=\"nofollow\">floorEntry</a> and related methods are not <code>public</code>. My current \"dirty\" solution is forcing them with reflection (in Scala):</p>\n\n<pre><code>val pt = new PatriciaTrie[String]()\nval method = pt.getClass.getSuperclass.getDeclaredMethod(\"floorEntry\", classOf[Object])\nmethod.setAccessible(true)\n// and then for retrieving the entry for floor(key) \nval entry = method.invoke(pt, key).asInstanceOf[Entry[String, String]]\n</code></pre>\n\n<p>Is there any clean way to have the same functionality? Why this methods are not publicly available?</p>\n","question_id":32539513,"tags":["java","scala","reflection","apache-commons-collection","patricia-trie"],"score":1,"accepted_answer_id":32539860,"is_answered":true,"view_count":150},{"owner":{"profile_image":"https://www.gravatar.com/avatar/367b7e33b6df6d9ec40dab06974f84af?s=256&d=identicon&r=PG","account_id":176500,"user_type":"registered","user_id":407236,"link":"https://stackoverflow.com/users/407236/tom-tucker","reputation":11736,"display_name":"Tom Tucker","accept_rate":94},"content_license":"CC BY-SA 2.5","link":"https://stackoverflow.com/questions/4542129/how-do-i-get-a-method-of-a-nested-property","last_activity_date":1617210812,"creation_date":1293487322,"answer_count":5,"title":"How do I get a Method of a nested property?","body":"<p>I have a class Foo that a property of the type Bar.</p>\n\n<pre><code>public class Foo {\n    public Bar getBar() {\n\n    }\n}\n\npublic class Bar {\n    public String getName();\n}\n</code></pre>\n\n<p>Is there a helper class or method that gets you a <code>java.lang.reflect.Method</code> object of the name property of <code>Bar</code>, using <code>Foo.class</code> and \"bar.name\"?</p>\n\n<p>There is a class called <code>PropertyUtils</code> in Commons BeanUtils, but its <code>getPropertyDescriptor()</code> only works for <code>Object</code> instances, not <code>Class</code> instances.</p>\n\n<p>I realize it's not hard at all to implement one, but I'd like to leverage what's already available.</p>\n\n<p>Also, the fact that I need a Method object is not a result of bad design(hope not). What I'm working on is pretty much a JavaBeans editor.</p>\n\n<p>Thanks!</p>\n","question_id":4542129,"tags":["java","reflection","javabeans"],"score":2,"accepted_answer_id":4542217,"is_answered":true,"view_count":4109,"last_edit_date":1293488524},{"owner":{"profile_image":"https://www.gravatar.com/avatar/ee43ba451b06e62437c0cda87d01fa66?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":6539656,"user_type":"registered","user_id":5057736,"link":"https://stackoverflow.com/users/5057736/pavel-k","reputation":11090,"display_name":"Pavel_K","accept_rate":84},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/61011291/how-to-get-class-which-invokes-static-method","last_activity_date":1586251319,"creation_date":1585914725,"answer_count":2,"title":"How to get class which invokes static method?","body":"<p>This is my code:</p>\n\n<pre><code>class A {\n\n    public static void doIt() {\n        //Class currentClass = new Object() { }.getClass().getEnclosingClass();\n        //Class currentClass = MethodHandles.lookup().lookupClass();\n        String currentClass = Thread.currentThread().getStackTrace()[1].getClassName();\n        System.out.println(\"CALLING CLASS:\" + currentClass);\n    }\n}\n\nclass B extends A { }\n\npublic class NewMain {\n\n    public static void main(String[] args) {\n        A.doIt();\n        B.doIt();\n    }\n}\n</code></pre>\n\n<p>As you see <code>doIt</code> method can be called by <code>A</code> and <code>B</code> classes. In <code>doIt</code> I want to know what class was used to call method (<code>A</code> or <code>B</code>). Is it possible? Three solutions I tried didn't work - it always says <code>A</code> class.</p>\n","question_id":61011291,"tags":["java","reflection"],"score":1,"accepted_answer_id":61012840,"is_answered":true,"view_count":305,"last_edit_date":1585914888},{"owner":{"profile_image":"https://www.gravatar.com/avatar/868c4addb3820f7dd3c21c9e8d95ce6e?s=256&d=identicon&r=PG","account_id":957148,"user_type":"registered","user_id":982247,"link":"https://stackoverflow.com/users/982247/user982247","reputation":91,"display_name":"user982247","accept_rate":0},"content_license":"CC BY-SA 3.0","link":"https://stackoverflow.com/questions/10723952/making-java-class-non-final-via-reflection-api","last_activity_date":1586239312,"creation_date":1337789738,"answer_count":3,"title":"Making Java Class non-final via Reflection API","body":"<p>I have a Java class similar to the following one:</p>\n\n<pre><code>public final class Node {\n    public Node() {}\n}\n</code></pre>\n\n<p>I have learned already how to change change the accessibility of 'final' fields via the reflection API, but is this also possible for classes?\nCan I turn a final class into a non-final class at runtime?</p>\n","question_id":10723952,"tags":["java","reflection"],"score":6,"is_answered":true,"view_count":1839},{"owner":{"profile_image":"https://www.gravatar.com/avatar/ca31bde95701e8f0684585fc6e25172d?s=256&d=identicon&r=PG","account_id":127164,"user_type":"registered","user_id":324152,"link":"https://stackoverflow.com/users/324152/mralwasser","reputation":15713,"display_name":"MRalwasser","accept_rate":63},"content_license":"CC BY-SA 2.5","link":"https://stackoverflow.com/questions/3298130/how-to-create-synthetic-fields-in-java","last_activity_date":1586156654,"creation_date":1279706974,"answer_count":3,"title":"How to create synthetic fields in java?","body":"<ol>\n<li><p>How can synthetic fields be created in Java? </p></li>\n<li><p>Can synthetic fields in java only be created at runtime?\nIf not: Is there a standard-compliant way to this at compile time (without changing some bytes in the class file)</p></li>\n</ol>\n","question_id":3298130,"tags":["java","reflection"],"score":10,"accepted_answer_id":3298144,"is_answered":true,"view_count":4542},{"owner":{"profile_image":"https://i.stack.imgur.com/vNPdg.jpg?s=256&g=1","account_id":14171,"user_type":"registered","user_id":28922,"link":"https://stackoverflow.com/users/28922/vinzz","reputation":3978,"display_name":"Vinzz","accept_rate":91},"content_license":"CC BY-SA 2.5","link":"https://stackoverflow.com/questions/1782598/with-java-reflection-how-to-instantiate-a-new-object-then-call-a-method-on-it","last_activity_date":1586018560,"creation_date":1258976137,"answer_count":6,"title":"With Java reflection how to instantiate a new object, then call a method on it?","body":"<p>I'm pretty new to Java, and I'm facing a reflection issue.</p>\n\n<p>Let's say i have to dynamically call the method <code>fooMethod</code> on an instance of the class <code>Foobar</code></p>\n\n<p>I got so far an instance of <code>Foobar</code> with: </p>\n\n<pre><code>Object instance = Class.forName(\"Foobar\").newInstance();\n</code></pre>\n\n<p>Let's say I know there's a method <code>fooMethod</code> on this object (I can even check this with <code>Class.forName(\"Foobar\").getDeclaredMethods()</code> ) , how to call it, please?</p>\n","question_id":1782598,"tags":["java","reflection"],"score":28,"accepted_answer_id":1782618,"is_answered":true,"view_count":66193,"last_edit_date":1258979368},{"owner":{"profile_image":"https://www.gravatar.com/avatar/305d3e8287fc271bb9bf17d9493efda2?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":6293136,"user_type":"registered","user_id":4890086,"link":"https://stackoverflow.com/users/4890086/amaille","reputation":65,"display_name":"amaille"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/61014998/how-to-verify-a-java-lang-reflect-method-known-only-from-reflection-was-called-o","last_activity_date":1586000740,"creation_date":1585926975,"answer_count":1,"title":"How to verify a java.lang.reflect.Method known only from reflection was called on an object","body":"<p>Given a java.lang.reflect.Method object obtained through reflection, how can I test that this Method was called on a given object ?</p>\n\n<p>Here is an example code :</p>\n\n<pre class=\"lang-java prettyprint-override\"><code>MyClass obj = mock(MyClass.class);\ninjectInTestedObject(obj, testedObj);\n\nString myMethodIWantToCheckName = retrieveMethodNameBySomeMeans();\nMethod myMethodIWantToCheck =\n  Arrays.asList(MyClass.class.getMethods())\n    .stream()\n    .filter(method -&gt; method.getName().equals(myMethodIWantToCheckName))\n    .findFirst()\n    .get();\n</code></pre>\n\n<p>Now I'd like to check if <code>myMethodIWantToCheck</code> was called on <code>obj</code>.</p>\n\n<p>Basically it's the same functionality as <code>verify</code> from Mockito but without knowing the method at compile time.</p>\n\n<p>Is there any way ? Any library already implementing this ?</p>\n","question_id":61014998,"tags":["java","unit-testing","reflection","mocking"],"score":1,"is_answered":true,"view_count":582},{"owner":{"profile_image":"https://www.gravatar.com/avatar/ebcadd97b19fd059bb7b8e5f83e7f928?s=256&d=identicon&r=PG","account_id":2301931,"user_type":"registered","user_id":5182503,"link":"https://stackoverflow.com/users/5182503/thatsme","reputation":123,"display_name":"ThatsMe"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/61015214/how-to-get-class-in-the-field-value-using-reflection","last_activity_date":1585935806,"creation_date":1585927677,"answer_count":1,"title":"How to get class in the field value using reflection?","body":"<p>Consider the following code</p>\n\n<pre><code>class Foo {\n\n}\n\nclass Bar {\n    private Foo foo = new Foo();\n}\n</code></pre>\n\n<p>Is it possible in <code>Foo</code> class to get the class of <code>foo</code> field. I mean, I want in <code>Foo</code> to get <code>Bar</code> class. The question is of course about reflection, but not about <code>new Foo(Bar.class)</code>.</p>\n","question_id":61015214,"tags":["java","reflection"],"score":0,"accepted_answer_id":61017551,"is_answered":true,"view_count":77},{"owner":{"user_type":"does_not_exist","display_name":"user5132301"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/61014647/non-nullable-type-throwing-kotlinnullpointerexception","last_activity_date":1585925827,"creation_date":1585925827,"answer_count":0,"title":"Non nullable type throwing KotlinNullPointerException","body":"<p>I have the following class in java</p>\n\n<pre><code>public class MyZClass1_ {\n\n    public int x = 100;\n\n}\n</code></pre>\n\n<p>and that test in kotlin</p>\n\n<pre><code>@TestInstance(TestInstance.Lifecycle.PER_CLASS)\nclass _01_SO_KotlinReflectionAccessorReturnTypeKotlinNull {\n\n    @Test\n    fun demonstrate_returnTypeReflectionOfAccessorFunctionInJavaClassThrowsKotlinNull() {\n        val zClass1_ = MyZClass1_::class\n        for (declaredProperty in zClass1_.declaredMemberProperties) {\n            val propertyGetter = declaredProperty.getter\n            assertNotNull(propertyGetter)\n            try {\n                val returnType = propertyGetter.returnType\n            } catch (ex: KotlinNullPointerException) {\n                ex.printStackTrace()\n            }\n        }\n    }\n\n}\n</code></pre>\n\n<ul>\n<li><code>propertyGetter</code> is not null (as asserted)</li>\n<li><code>propertyGetter.returnType</code> has a non-nullable type <code>KType</code></li>\n<li>The problem is that the line <code>val returnType = propertyGetter.returnType</code> throws a <code>KotlinNullPointerException</code>.</li>\n<li>Why is that? Am i missing something?</li>\n</ul>\n","question_id":61014647,"tags":["java","kotlin","reflection","nullpointerexception"],"score":2,"is_answered":false,"view_count":51},{"owner":{"profile_image":"https://www.gravatar.com/avatar/b1b5e172443aa2024adde9beb5a72b25?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":18089135,"user_type":"registered","user_id":13149219,"link":"https://stackoverflow.com/users/13149219/utsav10","reputation":450,"display_name":"Utsav10"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/61001701/get-the-original-class-if-casted-to-its-implemented-interface","last_activity_date":1585865705,"creation_date":1585863916,"answer_count":1,"title":"Get the original class if casted to its implemented interface","body":"<p>Assume a class as follows</p>\n\n<pre><code>interface Dummy{\n}\n\nclass Funny implements Dummy {\n}\n</code></pre>\n\n<p>Now I want to find a way to retrieve Class of a <strong>Funny</strong> object even if it is cast to <strong>Dummy</strong></p>\n","question_id":61001701,"tags":["java","reflection"],"score":0,"accepted_answer_id":61001763,"is_answered":true,"view_count":44,"last_edit_date":1585865705},{"owner":{"profile_image":"https://lh3.googleusercontent.com/-3oHOZdsUW0c/AAAAAAAAAAI/AAAAAAAAAAA/AAKWJJM8sG3pAQag1nLucMVgGmxwgiv0WQ/photo.jpg?sz=256","account_id":18126526,"user_type":"registered","user_id":13182012,"link":"https://stackoverflow.com/users/13182012/axel-w%c3%b6lfel","reputation":1,"display_name":"Axel W&#246;lfel"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/60968726/problem-with-com-google-common-reflect-classpath","last_activity_date":1585736638,"creation_date":1585736638,"answer_count":0,"title":"Problem with com.google.common.reflect.ClassPath","body":"<p>can someone please tell me what im doing wrong, because at this point it's getting really frustrating.</p>\n\n<pre><code>public List&lt;Test&gt; loadObjectsFromPackage(String url) throws IOException {\n    return ClassPath.from(this.getClass().getClassLoader())\n            .getTopLevelClassesRecursive(url)\n            .stream()\n            .map(ClassPath.ClassInfo::load)\n            .filter(Test.class::isAssignableFrom)\n            .map(clazz -&gt; {\n                try {\n                    return (Test) clazz.newInstance();\n                } catch (InstantiationException | IllegalAccessException e) {\n                    e.printStackTrace();\n                    return null;\n                }\n            })\n            .collect(Collectors.toList());\n}\n</code></pre>\n\n<p>So what im trying to do is load an list of objects, which are assigned to a subclass, from a package.</p>\n","question_id":60968726,"tags":["java","classpath","reflect"],"score":0,"is_answered":false,"view_count":179},{"owner":{"profile_image":"https://i.stack.imgur.com/92uEZ.jpg?s=256&g=1","account_id":16765025,"user_type":"registered","user_id":12118888,"link":"https://stackoverflow.com/users/12118888/payel-senapati","reputation":1190,"display_name":"Payel Senapati"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/60910846/explanation-and-proper-format-of-parametertypes-in-java-lang-class-getmethod","last_activity_date":1585681706,"creation_date":1585462990,"answer_count":2,"title":"Explanation and proper format of &quot;parameterTypes&quot; in &quot;java.lang.Class.getMethod()&quot; method","body":"<p>I have the following code -</p>\n\n<p><code>MyInterface.java</code> -</p>\n\n<pre><code>    default int getNumber() {\n        System.out.print(\"Number: \");\n        return in.nextInt();\n    }\n\n    default void displayNumber(int num) {\n        System.out.println(\"Number: \" + num);\n    }\n</code></pre>\n\n<p><code>Main.java</code> -</p>\n\n<pre><code>        int num;\n\n        MyInterface obj = new MyInterface() {\n        };\n\n        num = (int) obj.getClass().getMethod(\"getNumber\").invoke(obj);\n        obj.getClass().getMethod(\"displayNumber\", parameterType).invoke(obj);\n\n</code></pre>\n\n<p>I have left out the <code>exceptions</code> for clarity purpose</p>\n\n<p>Here I have created the <code>interface</code> - <code>MyInterface</code> with two <code>methods</code> -</p>\n\n<p>One <code>method</code> reads a number and returns it.</p>\n\n<p>The other <code>method</code> takes a number as <code>parameter</code> and prints it.</p>\n\n<p>In <code>Main</code> <code>method</code> I have created an <code>inner class</code> to implement the <code>interface</code></p>\n\n<p>Now using <code>reflection</code>  and <code>getMethod()</code> I am able to successfully call the first <code>method</code> to read a number.</p>\n\n<p>But I don't know the proper format to pass an <code>argument</code> using <code>getMethod()</code> and hence I am unable to successfully call the second <code>method</code>.</p>\n\n<p>Here, what should be in place of <code>parameterType</code>?</p>\n","question_id":60910846,"tags":["java","reflection","format","parameter-passing","inner-classes"],"score":0,"accepted_answer_id":60911107,"is_answered":true,"view_count":493},{"owner":{"profile_image":"https://www.gravatar.com/avatar/9ef8a1b5663958e411ef9e0f5f3eee0c?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":15094178,"user_type":"registered","user_id":10893136,"link":"https://stackoverflow.com/users/10893136/user322950","reputation":11,"display_name":"user322950"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/56598333/to-list-names-of-list-of-public-fields-declared-in-class-without-fields-inherite","last_activity_date":1560516111,"creation_date":1560515710,"answer_count":0,"title":"to list names of List of public fields declared in class without fields inherited from parent classes","body":"<p>I need to implement getPublicFields method to list names of public fields declared in class the object belongs to. Fields inherited from parent classes should be omitted. Field names should be sorted in lexical order.</p>\n\n<p>What I am doing wrong?</p>\n\n<pre><code>/**\n Get sorted list of public fields the object declares (inherited fields should be skipped).\n */\nclass FieldGetter {\n\n    public String[] getPublicFields(Object object) {\n\n    Field[] fieldsObject = object.getClass().getDeclaredFields();\n    ArrayList&lt;String&gt; fieldsString = new ArrayList&lt;&gt;();\n    for (Field fields : fieldsObject) {\n        if (Modifier.isPublic(fields.getModifiers())){\n            fieldsString.add(fields.toString());\n        }\n    }\n    String[]result = fieldsString.toArray(new String[fieldsString.size()]);\n    Arrays.sort(result);\n    return result;\n\n\n }\n}\n</code></pre>\n","question_id":56598333,"tags":["java","reflection"],"score":1,"is_answered":false,"view_count":135,"last_edit_date":1560516111},{"owner":{"profile_image":"https://www.gravatar.com/avatar/4faf33e2034c93c40eb69bd245f42414?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":12803347,"user_type":"registered","user_id":9263926,"link":"https://stackoverflow.com/users/9263926/henity","reputation":3,"display_name":"Henity"},"content_license":"CC BY-SA 3.0","link":"https://stackoverflow.com/questions/48648277/using-a-class-from-another-folder-java","last_activity_date":1560315295,"creation_date":1517936681,"answer_count":0,"title":"Using a class from another folder - JAVA","body":"<p>I have a java file with no main (Call.java) with a set of methods. I have another java file that I want to call the constructor in Call.java. Here is the structure:\n<a href=\"https://i.stack.imgur.com/dSXfL.png\" rel=\"nofollow noreferrer\">link to file structure</a></p>\n\n<p>I'm using the command-line to run java programs.</p>\n\n<p>My question is: how can I do so without getting an error</p>\n\n<p>Source code:\nClass:</p>\n\n<pre><code>import java.util.*;\n\npublic class Call{\n    private int userTypedInt;\n    Scanner userInput = new Scanner(System.in);\n\n    Call(){\n        while(true){\n            mainMenu();\n        }\n    }\n\n    public void mainMenu(){\n        System.out.println(\"\\n\\t\\t####| Main Menu |#### \\n\");\n        System.out.println(\"\\t\\t0. Exit the program\");\n        System.out.println(\"\\t\\t1. Option\");\n\n        // check that the user typed a number - specifically an int \n        try{\n            System.out.print(\"\\nEnter a choice: \");\n            userTypedInt = userInput.nextInt();\n            path(userTypedInt);\n        }catch(InputMismatchException e){\n            System.out.println(\"\\n\\t\\tInvalid entry\");\n            userInput.nextLine(); // clears the buffer\n        }\n    }\n\n    public void path(int pick){\n        switch(pick){\n            case 0:\n                userInput.close();\n                System.exit(0);\n                break;\n            case 1:\n                break;\n            default:\n                System.out.println(\"\\t\\tInvalid Entry\");\n        }\n    }\n}\n</code></pre>\n\n<p>Test file:</p>\n\n<pre><code>public class Test{\n    public static void main(String[] args){\n        System.out.println(\"Online\");\n        new Call();\n\n    }\n}\n</code></pre>\n","question_id":48648277,"tags":["java","class","reflection","import"],"score":0,"is_answered":false,"view_count":824,"last_edit_date":1517938466},{"owner":{"profile_image":"https://www.gravatar.com/avatar/a1d1e09e3dfe766a104909dadf8ae5ca?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":12232920,"user_type":"registered","user_id":8928311,"link":"https://stackoverflow.com/users/8928311/zwar","reputation":53,"display_name":"ZWar"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/56523704/problem-with-iterating-a-nd-array-with-reflection-in-java","last_activity_date":1560160862,"creation_date":1560158848,"answer_count":1,"title":"Problem with iterating a Nd array with reflection in Java","body":"<p>Alright so I want to print all of the elements in a random N dimensional array via reflection. The solution works great except I have N-1 empty arrays in the end of the <code>arraysString</code> string. For example:</p>\n\n<pre><code>private int[] arr = {3, 4, 5};\nprivate int[][] arrs = {{3, 4}, {3, 4, 5}, {3}};\n</code></pre>\n\n<p>Well when I try to serialize the first array, it will print -> [3, 4, 5], but when I print the second one -> [3, 4][3, 4, 5][3][] is printed. I am confused as to why this is happening. Here is my function:</p>\n\n<pre><code>private void serializeToArray(Object array, List&lt;String&gt; arraysAsString) {\n\n    StringBuilder builder = new StringBuilder();\n    List&lt;String&gt; arrayOutputs = new ArrayList&lt;&gt;();\n\n    int length = Array.getLength(array);\n    builder.append('[');\n    for (int i = 0; i &lt; length; i++) {\n        Object arrayElement = Array.get(array, i);\n        if (isArray(arrayElement)) {\n            serializeToArray(arrayElement, arraysAsString);\n            continue;\n        }\n        arrayOutputs.add('\"' + arrayElement.toString() + '\"');\n    }\n    builder.append(String.join(\",\", arrayOutputs));\n    builder.append(']');\n\n    arraysAsString.add(builder.toString());\n}\n</code></pre>\n\n<p>isArray -></p>\n\n<pre><code>protected boolean isArray(Object obj){\n    return obj.getClass().isArray();\n}\n</code></pre>\n","question_id":56523704,"tags":["java","reflection"],"score":1,"accepted_answer_id":56524004,"is_answered":true,"view_count":31,"last_edit_date":1560159335},{"owner":{"profile_image":"https://i.stack.imgur.com/1J90h.jpg?s=256&g=1","account_id":5313808,"user_type":"registered","user_id":4239282,"link":"https://stackoverflow.com/users/4239282/mohd","reputation":191,"display_name":"Mohd","accept_rate":77},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/56493196/reflection-npe-when-getting-field-value","last_activity_date":1560011441,"creation_date":1559905769,"answer_count":3,"title":"Reflection...NPE when getting field value","body":"<p>I have this POJO class :</p>\n\n<pre><code>  @Component\n  public class ClassOne{\n    public int  id;\n    public String fname;\n    public String lname;\n    public String    code;\n\n    super constructor\n    fields constructor\n    getters &amp; setters\n   }\n</code></pre>\n\n<p>I have this service class :</p>\n\n<pre><code>   @Service\n   public  class ClassOneServiceImpl implements ClassOneService{\n\n  public ClassOneServiceImpl{}\n\n  @override\n  public boolean addUser(String fname,String lname,String code){\n\n    Class&lt;?&gt; theClass = \n    Class.forName(\"com.somepackage.ClassOne\");\n    Constructor&lt;?&gt; theClassConstructor = \n   theClass.getConstructor(String.class, String.class,String.class);\n    ClassOne theClassObj = (ClassOne) \n   theClassConstructor.newInstance(\"fname\",\"lname\",\"code\");\n\n    Field fnameField = theClass.getDeclaredField(\"fname\");\n    Field lnameField = theClass.getDeclaredField(\"lname\");\n    Field codeField = theClass.getDeclaredField(\"code\");\n\n    System.out.println(\"Field name is \" + \n    fnameField.getName());  //I get the Field's name\n\nString fnameStr =(String) \n       fnameField.get(theClassObj);  //the NPE caused here \nString lnameStr =(String) \n       lnameField.get(theClassObj);\n\n\n    System.out.println(fnameStr);  //here getting null\n\n    ...here is the code to persist the form's field data .\n\n  }\n\n}\n</code></pre>\n\n<p>Obviously the \"theClassObj\" is not been instantiated,since the service class has no main method ...\nWhat's my mistake &amp; how to get the instance in this case ?</p>\n\n<p>I tried place the instance from within the service class constructor..didn't work.</p>\n\n<pre><code>  java.lang.NullPointerException: null\n</code></pre>\n","question_id":56493196,"tags":["java","spring","reflection"],"score":-3,"is_answered":false,"view_count":155,"last_edit_date":1559909585},{"owner":{"profile_image":"https://www.gravatar.com/avatar/c30b290f28a1b3ceb9f39d65e88b4339?s=256&d=identicon&r=PG","account_id":917815,"user_type":"registered","user_id":950218,"link":"https://stackoverflow.com/users/950218/sam-palmer","reputation":1695,"display_name":"Sam Palmer","accept_rate":72},"content_license":"CC BY-SA 3.0","link":"https://stackoverflow.com/questions/36644349/is-using-java-reflection-bad-practice","last_activity_date":1559897082,"creation_date":1460715269,"answer_count":2,"title":"Is using Java Reflection Bad Practice?","body":"<p>I am building an application for a client and I am in the situation where I need to have the ability to reference a field value via a string, i.e the users uses a string to define which field they want to change the value of, this is part of an abstract framework so technically I don't know the name of the fields they desire to change. Of course I could do this using hash maps, but I am considering using java reflection as this allows the fields to stay as fields of the object rather than the values being coded into a hash map. I have used reflection for my own personal work, but I was wondering if using Java reflection is actually bad practice, and I should stick to the hashmap methodology. </p>\n\n<p>(Any other suggestions for solving the design problem described are also appreciated)</p>\n\n<p>Thanks</p>\n","question_id":36644349,"tags":["java","design-patterns","reflection","design-principles"],"score":3,"accepted_answer_id":36645109,"is_answered":true,"view_count":4086,"last_edit_date":1460715402},{"owner":{"profile_image":"https://i.stack.imgur.com/bTu4R.png?s=256&g=1","account_id":9081897,"user_type":"registered","user_id":6761451,"link":"https://stackoverflow.com/users/6761451/david-geirola","reputation":634,"display_name":"David Geirola"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/42488711/play-framework-2-5-12-get-method-from-call","last_activity_date":1559839371,"creation_date":1488206968,"answer_count":2,"title":"Play Framework 2.5.12 - Get Method from Call","body":"<p>i need to get the method called from <strong>play.api.mvc.Call</strong> instance.\nI have noted the methods of my controllers and using reverse routing i need to check Those annotations.</p>\n\n<p>I'm using Play Framework 2.5.12</p>\n\n<p>Example:</p>\n\n<p>Annotation:</p>\n\n<pre><code>@Retention(RetentionPolicy.RUNTIME)\n@Target({ElementType.METHOD, ElementType.TYPE})\npublic @interface MyAnnotation{\n}\n</code></pre>\n\n<p>Controller:</p>\n\n<pre><code>public class MyController extends Controller {\n\n    @MyAnnotation\n    public Result home(int index){\n      return ok(index);\n    }\n}\n</code></pre>\n\n<p>Class:</p>\n\n<pre><code>public class MyClass{\n\n    private Call call;\n\n    public MyClass(Call call){\n      this.call = call;\n    }\n\n    public boolean hasAnnotation(){\n      //TODO\n      return call.getControllerMethod().isAnnotationPresent(MyAnnotation.class);\n    }\n}\n</code></pre>\n\n<p>Use:</p>\n\n<pre><code>MyClass obj = new MyClass(routes.MyController.home(1));\nif(obj.hasAnnotation()){\n  //do something\n}\n</code></pre>\n\n<p>Clearly <code>call.getControllerMethod()</code> does not exist but i need some solution to obtain the method of controllers from URL or Call Instance.</p>\n\n<p>Thanks for the support.</p>\n","question_id":42488711,"tags":["java","reflection","playframework"],"score":0,"accepted_answer_id":45443202,"is_answered":true,"view_count":583,"last_edit_date":1559839371},{"owner":{"profile_image":"https://www.gravatar.com/avatar/e6d306e93da21f5b239cfe36d46b240c?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":4607811,"user_type":"registered","user_id":3736788,"link":"https://stackoverflow.com/users/3736788/gabriel","reputation":447,"display_name":"gabriel","accept_rate":62},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/56439219/java-check-for-existence-of-method-instead-of-nosuchmethodexception","last_activity_date":1559655223,"creation_date":1559633123,"answer_count":1,"title":"Java - Check for existence of method instead of NoSuchMethodException","body":"<p>In my code have a method that is supposed to invoke the method <code>doSomething</code> of an object. Upfront, it is not known if the object's class does have the public method or not. Until now, I used the following code:</p>\n\n<pre><code>try {\n  Method method = component.getClass().getMethod(\"doSomething\", Boolean.TYPE);\n  method.invoke(component, true);\n} catch (final NoSuchMethodException e) {\n  // do nothing as for some components the method \"doSomething\" simply does not exist\n} \n</code></pre>\n\n<p>I now wonder if I should try to avoid the <code>NoSuchMethodException</code>by checking if the object's class does have the public method <code>doSomething</code>. </p>\n\n<pre><code>final Method method = Arrays.stream(component.getClass().getMethods())\n      .filter(m -&gt; m.getName().equals(\"doSomething\")).findFirst().orElse(null);\nif (method != null) {\n  method.invoke(component, true);\n}\n</code></pre>\n\n<p>What do you think is better?</p>\n","question_id":56439219,"tags":["java","reflection"],"score":0,"accepted_answer_id":56445027,"is_answered":true,"view_count":65},{"owner":{"profile_image":"https://i.stack.imgur.com/h37DD.jpg?s=256&g=1","account_id":3260426,"user_type":"registered","user_id":2746110,"link":"https://stackoverflow.com/users/2746110/arefe","reputation":11579,"display_name":"Arefe","accept_rate":67},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/56440825/calling-a-private-static-void-method","last_activity_date":1559640172,"creation_date":1559639411,"answer_count":2,"title":"Calling a private static void method","body":"<p>I have a <code>private static void</code> method namely  <code>convertToIp</code> in the class <code>EllaDtoConverter</code> that has a private constructor. If I try to create an instance of the class, it throws an exception. The code is provided, </p>\n\n<pre><code>public final class EllaDtoConverter {\n\n    private EllaDtoConverter() {\n        throw new PrivateConstructorException();\n    }\n\nprivate static void convertToIp( final IrisBo irisBo, EllaRequestDto request ) {\n\n        if( !isNull( irisBo.getDevice() ) ) {\n            request.setIp( irisBo.getDevice().getIpAddress() );\n        }\n    }\n\n    // ..... some code \n}\n</code></pre>\n\n<p>I can create the instances of the  <code>IrisBo</code> and the <code>EllaRequestDto</code> and pass inside the method. Do I have an option to call the <code>convertToIp</code> method outside from another class (even with using the reflection)?</p>\n","question_id":56440825,"tags":["java","reflection","junit"],"score":0,"accepted_answer_id":56440946,"is_answered":true,"view_count":1621},{"owner":{"user_type":"does_not_exist","display_name":"user253202"},"content_license":"CC BY-SA 3.0","link":"https://stackoverflow.com/questions/3502674/why-is-reflection-slow","last_activity_date":1559630891,"creation_date":1282050378,"answer_count":5,"title":"Why is reflection slow?","body":"<p>Is it because we should load class (by <code>string</code> for example), create instance, then search for appropriate method, pack parameters, and then just invoke method? So most time is spent on these operations instead of explicit method invocation on an object, right?</p>\n","question_id":3502674,"tags":["java","performance","reflection"],"score":29,"accepted_answer_id":3502710,"is_answered":true,"view_count":10518,"last_edit_date":1390172434},{"owner":{"profile_image":"https://www.gravatar.com/avatar/52b89ec6c4467a2b015ad5b9d03b3679?s=256&d=identicon&r=PG&f=y&so-version=2","account_id":6711313,"user_type":"registered","user_id":5174650,"link":"https://stackoverflow.com/users/5174650/gayatri","reputation":152,"display_name":"Gayatri"},"content_license":"CC BY-SA 4.0","link":"https://stackoverflow.com/questions/56435377/is-it-possible-to-create-a-java-model-object-at-runtime-and-map-the-fields-from","last_activity_date":1559603292,"creation_date":1559601833,"answer_count":1,"title":"Is it possible to create a Java Model Object at runtime and map the fields from the Spring Batch Reader dynamically?","body":"<p>We are trying to make our spring batch jobs more generic. In this process, we want to make the model object that gets passed between reader, processor and writer generic/dynamic too.\nIf we store the table-name, column-name, type-name in the database, and fetch this info at run time, will we be able to create a model class on the fly, map the data read in the reader and pass it along to the writer?</p>\n\n<p>Is it possible to create MyClass at runtime and do the mappings based on the configuration?\nRowMapper doesnt accept generic ?\nSo, how do we specify it in the code without actually having an already compiled class at run time?</p>\n\n<p>public class MyRowMapper implements RowMapper {</p>\n\n<pre><code>@Override\npublic MyClass mapRow(ResultSet rs, int rowNum) throws SQLException {\n\n    MyClass myClass= new MyClass();\n            myClass.setName(rs.getString(\"Name\"));\n            myClass.setNumber(rs.getLong(\"Number\"));\n    return myClass;\n}\n\n}\n</code></pre>\n","question_id":56435377,"tags":["java","spring","reflection","spring-batch","spring-jdbc"],"score":0,"is_answered":true,"view_count":1297}]